package profiles:plugin;

interface types {
 
    record profile {
        display-name: option<string>,
        bio: option<string>,
        avatar: bool,
    }

    record contact {
        account: string,
        nickname: option<string>,
        email: option<string>,
        phone: option<string>,
    }


}

interface api {
    
    use host:common/types.{error};
    use types.{profile, contact};
    use sites:plugin/types.{file};


    upload-avatar: func(file: file, compression-quality: u8) -> result<_, error>;
    remove-avatar: func() -> result<_, error>;

    add-contact: func(new-contact: contact) -> result<_, error>;
    update-contact: func(updated-contact: contact) -> result<_, error>;
    remove-contact: func(account: string) -> result<_, error>;

    get-contacts: func() -> result<list<contact>, error>;

    set-profile: func(profile: profile);
}


world imports {
    import api;
}
