[package]
name = "staged-tx-pkg"
description = "Library for proposing and executing staged transactions"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "StagedTx"
services = ["staged-tx"]

[package.metadata.psibase.dependencies]
Supervisor = "0.21.0"
Sites = "0.21.0"
HttpServer = "0.21.0"

[lib]
crate-type = ["rlib"]

[dependencies]
staged-tx = { path = "service", version = "0.21.0" }
r-staged-tx = { path = "query-service", version = "0.21.0" }
staged-tx-plugin = { path = "plugin", version = "0.21.0" }
psibase-system-workspace-hack.workspace = true
