[package]
name = "registry"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.psibase]
server = "r-registry"
plugin = "plugin"

[package.metadata.psibase.dependencies]
HttpServer = "0.15.0"
Sites = "0.15.0"

[dependencies]
psibase = { path = "../../../../rust/psibase", version = "0.15.0" }
serde = { version = "1", features = ["derive"] }
async-graphql = "7.0.7"
serde_json = "1.0.120"
url = "2.5.2"

[dev-dependencies]
registry-pkg = { path = "..", version = "0.15.0" }
