[package]
name = "registry"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.psibase]
server = "r-registry"
plugin = "plugin"

[package.metadata.psibase.dependencies]
HttpServer = "0.19.0"
Sites = "0.19.0"

[dependencies]
psibase = { path = "../../../../rust/psibase", version = "0.19.0" }
serde = { workspace = true }
async-graphql = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }

[dev-dependencies]
registry-pkg = { path = "..", version = "0.19.0" }
