[package]
name = "evaluations-pkg"
description = "Facilitates the discovery of one or more groups' rank-ordered preferences over a list of elements"
version = "0.17.0"
rust-version = "1.64"
edition = "2021"
publish = false

[package.metadata.psibase]
package-name = "Evaluations"
services = ["evaluations"]

[package.metadata.psibase.dependencies]
HttpServer = "0.19.0"
Sites = "0.19.0"

[lib]
crate-type = ["rlib"]

[dependencies]
evaluations = { path = "service", version = "0.19.0" }
r-evaluations = { path = "query-service", version = "0.19.0" }
evaluations-plugin = { path = "plugin", version = "0.19.0" }
