package addpermone:plugin;

interface admin {
    // is-valid-request: func(caller: string, callee: string) -> bool;
    // get-perm: func(user: string, caller: string, method: string) -> bool;
    save-perm: func(user: string, caller: string, method: string);
    del-perm: func(caller: string, method: string);
}

world impl {
    include host:common/imports;
    include transact:plugin/imports;
    include sites:plugin/imports;
    include clientdata:plugin/imports;
    include accounts:plugin/imports;

    export admin;
    export api;
    export queries;
}
