package addpermone:plugin;

interface admin {
    save-perm: func(caller: string, method: string);
    del-perm: func(caller: string, method: string);
}

world impl {
    include host:common/imports;
    include transact:plugin/imports;
    include sites:plugin/imports;
    include clientdata:plugin/imports;
    include accounts:plugin/imports;

    export admin;
    export api;
    export queries;
}
