[package]
name = "psibase-macros-lib"
version = "0.21.0"
edition = "2021"
license = "MIT"
description = "Macros to support psibase development"
repository = "https://github.com/gofractally/psibase"
homepage = "https://psibase.io"

[dependencies]
colored-diff = "0.2.3"
darling = "0.20.10"
proc-macro2 = "1.0.36"
syn = { version = "2.0.79" }
quote = "1.0.15"
proc-macro-error = "1.0.4"
