[workspace]
resolver = "2"
members = ["service", "plugin"]

[workspace.package]
version = "0.15.0"
rust-version = "1.64"
edition = "2021"
publish = false

[package]
name = "fractal-pkg"   # Crate name
description = "The Fractal service"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[package.metadata.psibase]
package-name = "Fractal"
services = ["fractal"]

[package.metadata.psibase.dependencies]
HttpServer = "0.15.0"
Sites = "0.15.0"

[lib]
crate-type = ["rlib"]

[dependencies]
fractal = { path = "service", version = "0.15.0" }
r-fractal = { path = "query-service", version = "0.15.0" }
# plugin = { path = "plugin", version = "0.15.0" }
