package base64:plugin;

/// Uses the URL-safe base64 encoding scheme.
interface url {
    use host:common/types.{error};

    /// Encodes a list of bytes into a base64url string.
    encode: func(input: list<u8>) -> string;

    /// Decodes a base64url string into a list of bytes.
    decode: func(input: string) -> result<list<u8>, error>;
}

world imports {
    import url;
}
