import {GraphFixtureData} from "./types"

export const graphFixtures: GraphFixtureData = {
  "cool-folks": {
    nodes: [
      { id: 0, name: "Paul", reputation: 2.5 },
      { id: 1, name: "Colion", reputation: 1.5 },
      { id: 2, name: "Matt", reputation: 2.0 },
      { id: 3, name: "Joshua", reputation: 5.2 },
      { id: 4, name: "Gregory", reputation: 1.3 },
      { id: 5, name: "Steven", reputation: 3.8 }
    ],
    attestations: [
      { source: { id: 0 }, target: { id: 1 } },
      { source: { id: 0 }, target: { id: 2 } },
      { source: { id: 0 }, target: { id: 3 } },
      { source: { id: 0 }, target: { id: 4 } },
      { source: { id: 0 }, target: { id: 5 } },
      { source: { id: 3 }, target: { id: 0 } },
      { source: { id: 3 }, target: { id: 4 } },
      { source: { id: 5 }, target: { id: 2 } },
      { source: { id: 4 }, target: { id: 2 } },
    ],
    "account-creations": [],
  },
  "complex-1": {
    nodes: [
      { id: 0, name: "James", reputation: 4.2, council: true },
      { id: 1, name: "Haruna", reputation: 2.2 },
      { id: 2, name: "Joseph", reputation: 3.2 },
      { id: 3, name: "Damian", reputation: 1.6 },
      { id: 4, name: "Isaac", reputation: 2.0 },
      { id: 5, name: "Rebecca", reputation: 1.8, council: true },
      { id: 6, name: "Jorge", reputation: 5.2 },
      { id: 7, name: "Kelly", reputation: 4.4, council: true },
      { id: 8, name: "Jen", reputation: 1.7 },
      { id: 9, name: "Barb", reputation: 3.8, council: true }
    ],
    attestations: [
      { source: { id: 0 }, target: { id: 1 } },
      { source: { id: 0 }, target: { id: 2 } },
      { source: { id: 0 }, target: { id: 3 } },
      { source: { id: 0 }, target: { id: 5 } },
      { source: { id: 3 }, target: { id: 0 } },
      { source: { id: 1 }, target: { id: 4 } },
      { source: { id: 1 }, target: { id: 2 } },
      { source: { id: 1 }, target: { id: 6 } },
      { source: { id: 1 }, target: { id: 8 } },
      { source: { id: 4 }, target: { id: 5 } },
      { source: { id: 2 }, target: { id: 6 } },
      { source: { id: 2 }, target: { id: 5 } },
      { source: { id: 2 }, target: { id: 4 } },
      { source: { id: 2 }, target: { id: 3 } },
      { source: { id: 6 }, target: { id: 7 } },
      { source: { id: 6 }, target: { id: 5 } },
      { source: { id: 6 }, target: { id: 3 } },
      { source: { id: 6 }, target: { id: 1 } },
      { source: { id: 3 }, target: { id: 8 } },
      { source: { id: 3 }, target: { id: 7 } },
      { source: { id: 3 }, target: { id: 4 } },
      { source: { id: 3 }, target: { id: 2 } },
      { source: { id: 3 }, target: { id: 1 } },
      { source: { id: 7 }, target: { id: 9 } },
      { source: { id: 7 }, target: { id: 8 } },
      { source: { id: 7 }, target: { id: 6 } },
      { source: { id: 8 }, target: { id: 5 } },
      { source: { id: 8 }, target: { id: 4 } },
      { source: { id: 8 }, target: { id: 9 } },
    ],
    "account-creations": [],
  },
  "sybil-1": {
    nodes: [
      { id: 0, name: "Rebecca", reputation: 4.0, council: true },
      { id: 1, name: "Haruna", reputation: 3.5 },
      { id: 2, name: "Joseph", reputation: 3.5 },
      { id: 3, name: "Damian", reputation: 3.5 },
      { id: 4, name: "Isaac", reputation: 3.5 },
      { id: 5, name: "James", reputation: 3.5, council: true },
      { id: 6, name: "Jorge", reputation: 3.5 },
      { id: 7, name: "Kelly", reputation: 3.5, council: true },
      { id: 8, name: "Jen", reputation: 3.5, council: true },
      { id: 9, name: "Barb", reputation: 3.5 }
    ],
    attestations: [
      { source: { id: 1 }, target: { id: 5 } },
      { source: { id: 5 }, target: { id: 2 } },
      { source: { id: 5 }, target: { id: 3 } },
      { source: { id: 4 }, target: { id: 1 } },
      { source: { id: 0 }, target: { id: 4 } },
      { source: { id: 2 }, target: { id: 6 } },
      { source: { id: 6 }, target: { id: 7 } },
      { source: { id: 3 }, target: { id: 8 } },
      { source: { id: 8 }, target: { id: 9 } },
    ],
    "account-creations": [],
  },
  "sybil-2": {
    nodes: [
      { id: 0, name: "James", reputation: 3.5, council: true },
      { id: 1, name: "Haruna", reputation: 3.5 },
      { id: 2, name: "Joseph", reputation: 3.5 },
      { id: 3, name: "Damian", reputation: 3.5 },
      { id: 4, name: "Isaac", reputation: 3.5 },
      { id: 5, name: "Rebecca", reputation: 3.5, council: true },
      { id: 6, name: "Jorge", reputation: 3.5 },
      { id: 7, name: "Kelly", reputation: 3.5 },
      { id: 8, name: "Jen", reputation: 3.5, council: true },
      { id: 9, name: "Barb", reputation: 3.5 }
    ],
    attestations: [
      { source: { id: 0 }, target: { id: 1 } },
      { source: { id: 0 }, target: { id: 2 } },
      { source: { id: 0 }, target: { id: 3 } },
      { source: { id: 1 }, target: { id: 4 } },
      { source: { id: 4 }, target: { id: 5 } },
      { source: { id: 2 }, target: { id: 6 } },
      { source: { id: 6 }, target: { id: 7 } },
      { source: { id: 3 }, target: { id: 8 } },
      { source: { id: 8 }, target: { id: 9 } },
    ],
    "account-creations": [],
  },
  "not-sybil-2": {
    nodes: [
      { id: 0, name: "Rebecca", reputation: 3.5, council: true },
      { id: 1, name: "Haruna", reputation: 3.5 },
      { id: 2, name: "Joseph", reputation: 3.5 },
      { id: 3, name: "Damian", reputation: 3.5 },
      { id: 4, name: "Isaac", reputation: 3.5 },
      { id: 5, name: "James", reputation: 3.5, council: true },
      { id: 6, name: "Jorge", reputation: 3.5 },
      { id: 7, name: "Kelly", reputation: 3.5, council: true },
      { id: 8, name: "Jen", reputation: 3.5 },
      { id: 9, name: "Barb", reputation: 3.5, council: true }
    ],
    attestations: [
      { source: { id: 1 }, target: { id: 5 } },
      { source: { id: 5 }, target: { id: 2 } },
      { source: { id: 5 }, target: { id: 3 } },
      { source: { id: 4 }, target: { id: 1 } },
      { source: { id: 0 }, target: { id: 4 } },
      { source: { id: 2 }, target: { id: 6 } },
      { source: { id: 6 }, target: { id: 7 } },
      { source: { id: 3 }, target: { id: 8 } },
      { source: { id: 8 }, target: { id: 9 } },
    ],
    "account-creations": [],
  },
  "depth-2.1": {
    nodes: [
      { id: 0, name: "James", reputation: 3.5, council: true },
      { id: 1, name: "Haruna", reputation: 3.5 },
      { id: 2, name: "Joseph", reputation: 3.5 },
      { id: 3, name: "Damian", reputation: 3.5 },
      { id: 4, name: "Isaac", reputation: 3.5 },
      { id: 5, name: "Rebecca", reputation: 3.5, council: true },
      { id: 6, name: "Jorge", reputation: 3.5 },
      { id: 7, name: "Kelly", reputation: 3.5 },
      { id: 8, name: "Jen", reputation: 3.5 },
      { id: 9, name: "Barb", reputation: 3.5 }
    ],
    attestations: [
      { source: { id: 0 }, target: { id: 1 } },
      { source: { id: 0 }, target: { id: 2 } },
      { source: { id: 0 }, target: { id: 3 } },
      { source: { id: 1 }, target: { id: 4 } },
      { source: { id: 4 }, target: { id: 5 } },
      { source: { id: 2 }, target: { id: 6 } },
      { source: { id: 6 }, target: { id: 7 } },
      { source: { id: 3 }, target: { id: 8 } },
      { source: { id: 8 }, target: { id: 9 } },
    ],
    "account-creations": [],
  },
  "complex-2": {
    nodes: [
      { id: 0, name: "James", reputation: 4.2 },
      { id: 1, name: "Haruna", reputation: 2.2 },
      { id: 2, name: "Joseph", reputation: 3.2 },
      { id: 3, name: "Damian", reputation: 1.6 },
      { id: 4, name: "Isaac", reputation: 2.0 },
      { id: 5, name: "Rebecca", reputation: 1.8, council: true },
      { id: 6, name: "Jorge", reputation: 5.2 },
      { id: 7, name: "Kelly", reputation: 4.4, council: true },
      { id: 8, name: "Jen", reputation: 1.7 },
      { id: 9, name: "Barb", reputation: 3.8 },
      { id: 10, name: "Alice", reputation: 4.2 },
      { id: 11, name: "Bob", reputation: 2.2 },
      { id: 12, name: "Carol", reputation: 3.2, council: true },
      { id: 13, name: "David", reputation: 1.6 },
      { id: 14, name: "Eduardo", reputation: 2.0 },
      { id: 15, name: "Fitz", reputation: 1.8 },
      { id: 16, name: "Greg", reputation: 5.2 },
      { id: 17, name: "Harry", reputation: 4.4, council: true },
      { id: 18, name: "Ivan", reputation: 1.7 },
      { id: 19, name: "Jerry", reputation: 3.8, council: true },
      { id: 20, name: "Karen", reputation: 4.2 },
      { id: 21, name: "Lara", reputation: 2.2 },
      { id: 22, name: "Miriam", reputation: 3.2 },
      { id: 23, name: "Nancy", reputation: 1.6 },
      { id: 24, name: "Oranthal", reputation: 2.0 },
      { id: 25, name: "Patty", reputation: 1.8 },
      { id: 26, name: "Randy", reputation: 5.2 },
      { id: 27, name: "Sarah", reputation: 4.4 },
      { id: 28, name: "Tilly", reputation: 1.7 },
      { id: 29, name: "Ursula", reputation: 3.8 },
      { id: 30, name: "Venus", reputation: 4.2, council: true },
      { id: 31, name: "Warren", reputation: 2.2 },
      { id: 32, name: "Zora", reputation: 3.2, council: true },
      { id: 33, name: "Alan", reputation: 1.6 },
      { id: 34, name: "Bernie", reputation: 2.0 },
      { id: 35, name: "Chris", reputation: 1.8 },
      { id: 36, name: "Deidre", reputation: 5.2 },
      { id: 37, name: "Ellie", reputation: 4.4 },
      { id: 38, name: "Fred", reputation: 1.7 },
      { id: 39, name: "Gary", reputation: 3.8 },
      { id: 40, name: "Hilda", reputation: 4.2 },
      { id: 41, name: "Illy", reputation: 2.2 },
      { id: 42, name: "Jill", reputation: 3.2 },
      { id: 43, name: "Kim", reputation: 1.6 },
      { id: 44, name: "Liam", reputation: 2.0 },
      { id: 45, name: "Mary", reputation: 1.8 },
      { id: 46, name: "Penny", reputation: 5.2 },
      { id: 47, name: "Rich", reputation: 4.4 },
      { id: 48, name: "Sheldon", reputation: 1.7 },
      { id: 49, name: "Tyrell", reputation: 3.8 }
    ],
    "account-creations": [
      { source: { id: 0 }, target: { id: 1 } },
      { source: { id: 0 }, target: { id: 2 } },
      { source: { id: 0 }, target: { id: 3 } },
      { source: { id: 0 }, target: { id: 4 } },
      { source: { id: 0 }, target: { id: 5 } },
      { source: { id: 0 }, target: { id: 6 } },
      { source: { id: 0 }, target: { id: 7 } },
      { source: { id: 0 }, target: { id: 8 } },
      { source: { id: 0 }, target: { id: 9 } },
      { source: { id: 1 }, target: { id: 10 } },
      { source: { id: 10 }, target: { id: 11 } },
      { source: { id: 10 }, target: { id: 12 } },
      { source: { id: 10 }, target: { id: 13 } },
      { source: { id: 10 }, target: { id: 14 } },
      { source: { id: 10 }, target: { id: 15 } },
      { source: { id: 10 }, target: { id: 16 } },
      { source: { id: 10 }, target: { id: 17 } },
      { source: { id: 10 }, target: { id: 18 } },
      { source: { id: 10 }, target: { id: 19 } },
      { source: { id: 2 }, target: { id: 20 } },
      { source: { id: 20 }, target: { id: 21 } },
      { source: { id: 20 }, target: { id: 22 } },
      { source: { id: 20 }, target: { id: 23 } },
      { source: { id: 20 }, target: { id: 24 } },
      { source: { id: 20 }, target: { id: 25 } },
      { source: { id: 20 }, target: { id: 26 } },
      { source: { id: 20 }, target: { id: 27 } },
      { source: { id: 20 }, target: { id: 28 } },
      { source: { id: 20 }, target: { id: 29 } },
      { source: { id: 3 }, target: { id: 30 } },
      { source: { id: 30 }, target: { id: 31 } },
      { source: { id: 30 }, target: { id: 32 } },
      { source: { id: 30 }, target: { id: 33 } },
      { source: { id: 30 }, target: { id: 34 } },
      { source: { id: 30 }, target: { id: 35 } },
      { source: { id: 30 }, target: { id: 36 } },
      { source: { id: 30 }, target: { id: 37 } },
      { source: { id: 30 }, target: { id: 38 } },
      { source: { id: 30 }, target: { id: 39 } },
      { source: { id: 4 }, target: { id: 40 } },
      { source: { id: 40 }, target: { id: 41 } },
      { source: { id: 40 }, target: { id: 42 } },
      { source: { id: 40 }, target: { id: 43 } },
      { source: { id: 40 }, target: { id: 44 } },
      { source: { id: 40 }, target: { id: 45 } },
      { source: { id: 40 }, target: { id: 46 } },
      { source: { id: 40 }, target: { id: 47 } },
      { source: { id: 40 }, target: { id: 48 } },
      { source: { id: 40 }, target: { id: 49 } },
    ],
    attestations: [
      { source: { id: 0 }, target: { id: 1 } },
      { source: { id: 0 }, target: { id: 2 } },
      { source: { id: 0 }, target: { id: 3 } },
      { source: { id: 0 }, target: { id: 5 } },
      { source: { id: 3 }, target: { id: 0 } },
      { source: { id: 1 }, target: { id: 4 } },
      { source: { id: 1 }, target: { id: 2 } },
      { source: { id: 1 }, target: { id: 6 } },
      { source: { id: 1 }, target: { id: 8 } },
      { source: { id: 4 }, target: { id: 5 } },
      { source: { id: 2 }, target: { id: 6 } },
      { source: { id: 2 }, target: { id: 5 } },
      { source: { id: 2 }, target: { id: 4 } },
      { source: { id: 2 }, target: { id: 3 } },
      { source: { id: 5 }, target: { id: 7 } },
      { source: { id: 5 }, target: { id: 6 } },
      { source: { id: 5 }, target: { id: 3 } },
      { source: { id: 5 }, target: { id: 1 } },
      { source: { id: 3 }, target: { id: 8 } },
      { source: { id: 3 }, target: { id: 7 } },
      { source: { id: 3 }, target: { id: 4 } },
      { source: { id: 3 }, target: { id: 2 } },
      { source: { id: 3 }, target: { id: 1 } },
      { source: { id: 7 }, target: { id: 9 } },
      { source: { id: 7 }, target: { id: 8 } },
      { source: { id: 7 }, target: { id: 6 } },
      { source: { id: 8 }, target: { id: 5 } },
      { source: { id: 8 }, target: { id: 4 } },
      { source: { id: 8 }, target: { id: 9 } },
      { source: { id: 9 }, target: { id: 1 } },
      { source: { id: 9 }, target: { id: 10 } },
      { source: { id: 9 }, target: { id: 15 } },
      { source: { id: 9 }, target: { id: 20 } },
      { source: { id: 9 }, target: { id: 30 } },
      { source: { id: 10 }, target: { id: 5 } },
      { source: { id: 10 }, target: { id: 14 } },
      { source: { id: 10 }, target: { id: 19 } },
      { source: { id: 10 }, target: { id: 24 } },
      { source: { id: 10 }, target: { id: 29 } },
      { source: { id: 11 }, target: { id: 15 } },
      { source: { id: 12 }, target: { id: 14 } },
      { source: { id: 14 }, target: { id: 12 } },
      { source: { id: 15 }, target: { id: 11 } },
      { source: { id: 16 }, target: { id: 10 } },
      { source: { id: 16 }, target: { id: 38 } },
      { source: { id: 17 }, target: { id: 9 } },
      { source: { id: 18 }, target: { id: 8 } },
      { source: { id: 19 }, target: { id: 21 } },
      { source: { id: 20 }, target: { id: 22 } },
      { source: { id: 21 }, target: { id: 24 } },
      { source: { id: 23 }, target: { id: 21 } },
      { source: { id: 23 }, target: { id: 29 } },
      { source: { id: 24 }, target: { id: 29 } },
      { source: { id: 25 }, target: { id: 28 } },
      { source: { id: 26 }, target: { id: 31 } },
      { source: { id: 27 }, target: { id: 32 } },
      { source: { id: 28 }, target: { id: 33 } },
      { source: { id: 29 }, target: { id: 35 } },
      { source: { id: 31 }, target: { id: 34 } },
      { source: { id: 31 }, target: { id: 48 } },
      { source: { id: 31 }, target: { id: 11 } },
      { source: { id: 32 }, target: { id: 42 } },
      { source: { id: 33 }, target: { id: 46 } },
      { source: { id: 34 }, target: { id: 48 } },
      { source: { id: 35 }, target: { id: 45 } },
      { source: { id: 35 }, target: { id: 19 } },
      { source: { id: 37 }, target: { id: 35 } },
      { source: { id: 38 }, target: { id: 34 } },
      { source: { id: 39 }, target: { id: 33 } },
      { source: { id: 40 }, target: { id: 37 } },
      { source: { id: 41 }, target: { id: 25 } },
      { source: { id: 42 }, target: { id: 23 } },
      { source: { id: 43 }, target: { id: 21 } },
      { source: { id: 44 }, target: { id: 28 } },
      { source: { id: 45 }, target: { id: 27 } },
      { source: { id: 46 }, target: { id: 14 } },
      { source: { id: 46 }, target: { id: 29 } },
      { source: { id: 47 }, target: { id: 12 } },
      { source: { id: 48 }, target: { id: 11 } },
      { source: { id: 49 }, target: { id: 19 } },
      { source: { id: 48 }, target: { id: 18 } },
    ]
  }
}

export default graphFixtures;