[package]
name = "r-tokens"
description = "RPC service for tokens"
version = "0.21.1"
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
psibase.workspace = true
serde.workspace = true
serde_json.workspace = true
tokens = { path = "../service", version = "0.21.1" }
async-graphql.workspace = true
serde-aux.workspace = true
