[package]
name = "r-tokens"
description = "RPC service for tokens"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
psibase.workspace = true
serde.workspace = true
serde_json.workspace = true
tokens = { path = "../service", version = "0.22.0" }
async-graphql.workspace = true
serde-aux.workspace = true
user-workspace-hack = { version = "0.1", path = "../../user-workspace-hack" }
