[package]
name = "token-stream"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.psibase]
postinstall = [
    { sender = "token-stream", service = "sites", method = "enablespa", data = { enable = true } },
    { sender = "token-stream", service = "tokens", method = "setUserConf", data = { index = 0, enabled = true } },
]

server = "r-token-stream"
plugin = "token-stream-plugin"
data = [{ src = "../ui/dist", dst = "/" }]

[dependencies]
psibase.workspace = true
psibase_macros.workspace = true
async-graphql.workspace = true
serde.workspace = true
serde_json.workspace = true
psibase-user-workspace-hack.workspace = true

[dev-dependencies]
token-stream-pkg = { path = "..", version = "0.22.0" }
