[package]
name = "branding-pkg"                                           # Crate name
description = "Allow operators to rebrand their network easily"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "Branding"
services = ["branding"]

[package.metadata.psibase.dependencies]
HttpServer = "0.22.0"
Sites = "0.22.0"

[lib]
crate-type = ["rlib"]

[dependencies]
branding = { path = "service", version = "0.22.0" }
branding-plugin = { path = "plugin", version = "0.22.0" }
psibase-user-workspace-hack.workspace = true
