[package]
name = "branding-pkg"
description = "Allow operators to rebrand their network easily"
version = "0.21.1"                                              # This package uses 0.21.1 while workspace default is 0.21.0
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "Branding"
services = ["branding"]

[package.metadata.psibase.dependencies]
HttpServer = "0.21.0"
Sites = "0.21.0"

[lib]
crate-type = ["rlib"]

[dependencies]
branding = { path = "service", version = "0.21.1" }
plugin = { path = "plugin", version = "0.21.1" }
