[package]
name = "brotli-codec-pkg"
description = "Compression/decompression library"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "BrotliCodec"
services = ["brotli-codec"]

[package.metadata.psibase.dependencies]
Supervisor = "0.21.0"
Sites = "0.21.0"
HttpServer = "0.21.0"

[lib]
crate-type = ["rlib"]

[dependencies]
brotli-codec = { path = "service", version = "0.21.0" }
brotli-codec-plugin = { path = "plugin", version = "0.21.0" }
serde = { version = "1.0", features = ["derive"] }
