[package]
name = "chainmail_package"
description = "Message-sending application"
version = "0.17.0"
rust-version = "1.64"
edition = "2021"
repository = "https://github.com/gofractally/psibase"
homepage = "https://psibase.io"
publish = false

[package.metadata.psibase]
package-name = "Chainmail"
services = ["chainmail"]

[package.metadata.psibase.dependencies]
HttpServer = "0.17.0"
Supervisor = "0.17.0"
Events = "0.17.0"
SetCode = "0.17.0"
Accounts = "0.17.0"
CommonApi = "0.17.0"
Sites = "0.17.0"


[lib]
crate-type = ["rlib"]

[dependencies]
chainmail = { path = "service", version = "0.17.0" }
chainmail-plugin = { path = "plugin", version = "0.17.0" }
