[workspace]
resolver = "2"
members = ["service", "plugin"]

[workspace.package]
version = "0.17.0"
rust-version = "1.64"
edition = "2021"
repository = "https://github.com/gofractally/psibase"
homepage = "https://psibase.io"
publish = false

[workspace.dependencies]
# Standardize external dependencies to enable build artifact sharing
wit-bindgen-rt = { version = "0.39.0", features = ["bitflags"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-graphql = "7.0.17"
anyhow = "1.0"

[package]
name = "chainmail_package"
description = "Message-sending application"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "Chainmail"
services = ["chainmail"]

[package.metadata.psibase.dependencies]
HttpServer = "0.17.0"
Supervisor = "0.17.0"
Events = "0.17.0"
SetCode = "0.17.0"
Accounts = "0.17.0"
CommonApi = "0.17.0"
Sites = "0.17.0"

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[lib]
crate-type = ["rlib"]

[dependencies]
chainmail = { path = "service", version = "0.17.0" }
plugin = { path = "plugin", version = "0.17.0" }
