[package]
name = "component-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
bitflags = "2.4.2"
wasm-compose = "0.201.0"
wasmparser = "0.201.0"
wit-component = "0.201.0"
wit-bindgen-rt = "0.22.0"
wit-parser = "0.201.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:component-parser"
