package component:account-sys;


interface types {
    record user {
        name: string,
        age: u8
    }

    record funccallparams {
        service: string,
        method: string,
        params: string
    }

}

interface imports {
   use types.{funccallparams};

   prnt: func(msg: string);
   funccall: func(msg: funccallparams);
   add-to-tx: func(msg: funccallparams);


}

interface token-sys {
    transfer: func(msg: string);
}

world example {

    import imports;
    import token-sys;

    use types.{user};
    export hire: func(user: user) -> string;

    export peoples: func(users: list<user>) -> string;

    export numbers: func(num1: u8, num2: u8, doubleup: bool) -> string;
    export strings: func(word: string) -> string;
    export call: func() -> string;
}
