/// The staged-tx plugin allows apps to set a "propose latch" for an account. What makes it a "latch" is that 
/// gets automatically unset after the completion of the call context in which it is set.
/// 
/// When the latch is set, server actions scheduled by plugins are staged by the current user
/// instead of being executed by the logged-in user. These actions are proposed for execution
/// by the account specified when enabling the latch.
package staged-tx:plugin;

interface api {
    use host:common/types.{error};

    /// This is a latch that is set for this callContext, and unset when the callContext is completed.
    /// It can only be called by the plugin of the currently active application.
    /// 
    /// `account` - The account on behalf of which the currently logged-in user is 
    ///             proposing transactions.
    set-propose-latch: func(account: string) -> result<_, error>;
}

world imports {
    import api;
}
