[workspace]
resolver = "2"
members = ["service", "auth-service"]

[workspace.package]
version = "0.20.0"
rust-version = "1.64"
edition = "2021"
publish = false

[package]
name = "credentials-pkg"
description = "Manages credentials and signing with credentials"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[package.metadata.psibase]
package-name = "Credentials"
services = ["credentials", "auth-cred"]

[package.metadata.psibase.dependencies]
#HttpServer = "0.20.0"
#Sites = "0.20.0"
AuthDelegate = "0.20.0"

[lib]
crate-type = ["rlib"]

[dependencies]
credentials = { path = "service", version = "0.20.0" }
auth-cred = { path = "auth-service", version = "0.20.0" }
