[package]
name = "staged-tx"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
publish = false

[package.metadata.psibase]
flags = ["isPrivileged"]
server = "r-staged-tx"
plugin = "staged-tx-plugin"
postinstall = [{ sender = "staged-tx", service = "staged-tx", method = "init" }]

[dependencies]
async-graphql.workspace = true
psibase.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2 = { version = "0.10" }
pem = { version = "3.0.4" }

[dev-dependencies]
staged-tx-pkg = { path = "..", version = "0.21.0" }
