[package]
name = "service"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
async-graphql = "4.0"
psibase = { version = "0.8.0", path = "../../../../rust/psibase" }

