package identity:plugin;

interface types {
    type account = string;
    type date-time = string;

    record attestation-graph-node {
        attester: string,
        attested-to: string,
        perc-high-confidence: f32,
        num-unique-attestations: u32,
    }
    type attestation-graph = list<attestation-graph-node>;

    /* an identity profile summarizes a member's identity attestations over a 3 month window.
        A Member profile will show % of high-confidence attestations (from unique attesters) with the total number of (unique) attesters, e.g., 83% of 12.
        Attestations from the same attester will simply replace the most recent attestation from that attester, to maintain the freshness of attestations, and
        the data that’s summarized in a Member profile will be a summary of the last 3 months of data.
        */
    record identity-attestation {
        attester: account,
        attested-to: account,
        confidence: f32,
        date: date-time,
    }
    record identity-summary {
        perc-high-confidence: f32,
        num-unique-attestations: u32,
    }
}

interface api {
    use common:plugin/types.{error};

    // calls Attestation service's attest("identity", ???)
    // The attestor attests (being something of a provider in this scenario), logging an event on chain, with a signature from the issuer (account)
    // which can always become a verifiable credential for someone else (more of a consumer in this equation)
    attest-identity-claim: func(subject: string, confidence: f32) -> result<_, error>;
    // impl: attestation:plugin.attest("identity", vc)
}

interface queries {
    use common:plugin/types.{error};
    use types.{attestation-graph, identity-summary, identity-attestation};

    /* identity attestation args:
        - subject: the username being attested to
        - confidence: a float representing a percentage confidence.
            The question an identity attestation is answering:
            How confident are you that this is a real person and that they are the person they claim to be?
            Generally, the expectation is for humans to only distinguish 5 useful degrees of confidence:
            1 I’m sure they're not who they claim to be (0%) --> 0.0
            2 Very unlikely to be who they claim to be (20%) --> 0.2
            3 50/50 chance (50%) --> 0.5
            4 High chance they are who they claim (75%) --> 0.75
            5 I’m very confident they are who they claim (90%+) --> 0.90
        */
    graph: func() -> result<attestation-graph, error>;
    // graph: func(subject: string, depth: u8) -> result<attestation-graph, error>;
    get-summary: func(subject: string) -> result<identity-summary, error>;
    get-history: func(subject: string) -> result<list<identity-attestation>, error>;
}

world identity {
    import common:plugin/server;
    import common:plugin/client;
    import accounts:plugin/accounts;
    export api;
    // export queries;
}