[package]
name = "subgroups-pkg"
description = "Generates subgroups given total population and allowed group size"
version = "0.19.0"
rust-version = "1.64"
edition = "2021"
publish = false


[package.metadata.psibase]
package-name = "Subgroups"
services = ["subgroups"]

[lib]
crate-type = ["rlib"]

[dependencies]
subgroups = { path = "service", version = "0.19.0" }
