[package]
name = "chainmail"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
publish = false

[package.metadata.psibase]
server = "chainmail"
plugin = "chainmail-plugin"
data = [{ src = "../ui/dist/", dst = "/" }]
postinstall = [{ sender = "chainmail", service = "chainmail", method = "init" }]

[dependencies]
psibase.workspace = true
async-graphql.workspace = true
serde.workspace = true
psibase-user-workspace-hack.workspace = true

[dev-dependencies]
chainmail_package = { path = "..", version = "0.22.0" }
