[workspace]
resolver = "2"
members = ["service", "query", "plugin"]

[workspace.package]
version = "0.16.0"
rust-version = "1.64"
edition = "2021"
publish = false

[package]
name = "registry-pkg"
description = "Registry for psibase apps"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "Registry"
services = ["registry"]

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[lib]
crate-type = ["rlib"]

[dependencies]
registry = { path = "service", version = "0.16.0" }
r-registry = { path = "query", version = "0.16.0" }
plugin = { path = "plugin", version = "0.16.0" }
