[package]
name = "registry-pkg"
description = "Registry for psibase apps"
version = "0.19.0"
rust-version = "1.64"
edition = "2021"
publish = false

[package.metadata.psibase]
package-name = "Registry"
services = ["registry"]


[lib]
crate-type = ["rlib"]

[dependencies]
registry = { path = "service", version = "0.19.0" }
r-registry = { path = "query", version = "0.19.0" }
registry-plugin = { path = "plugin", version = "0.19.0" }
