[workspace]
resolver = "2"
members = ["service", "plugin"]

[workspace.package]
version = "0.14.0"
rust-version = "1.64"
edition = "2021"
repository = "https://github.com/gofractally/psibase"
homepage = "https://psibase.io"
publish = false

[package]
name = "brotli_package"
description = "Compression/decompression library"
version.workspace = true
edition.workspace = true

[package.metadata.psibase]
package-name = "Brotli"
services = ["psi-brotli"]

[package.metadata.psibase.dependencies]
Supervisor = "0.14.0"
Sites = "0.14.0"
HttpServer = "0.14.0"

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[lib]
crate-type = ["rlib"]

[dependencies]
psi-brotli = { path = "service", version = "0.14.0" }
plugin = { path = "plugin", version = "0.14.0" }
serde = { version = "1.0", features = ["derive"] }
