[package]
name = "r-fractally"
description = "RPC service for fractally"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
psibase = { path = "../../../../rust/psibase/", version = "0.16.0" }
serde = "1.0"
serde_json = "1.0"
fractally = { path = "../service", version = "0.16.0" }
async-graphql = { version = "7.0.10" }
