[package]
name = "credentials-pkg"
description = "Manages credentials and signing with credentials"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "Credentials"
services = ["credentials"]

[package.metadata.psibase.dependencies]
Sites = "0.22.0"
Accounts = "0.22.0"

[lib]
crate-type = ["rlib"]

[dependencies]
credentials = { path = "service", version = "0.22.0" }
credentials-plugin = { path = "plugin", version = "0.22.0" }
system-workspace-hack = { version = "0.1", path = "../system-workspace-hack" }
