[package]
name = "example"
description = "Test contract #2"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition = "2021"
publish = false

[package.metadata.psibase]
package-name = "TestContract2"
# flags = []
server = "example"

[package.metadata.psibase.dependencies]
HttpServer = "0.14.0"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
psibase_macros = { version = "0.14.0", path = "../psibase_macros" }
psibase = { version = "0.14.0", path = "../psibase" }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
async-graphql = "7.0.6"
