[package]
name = "test_contract_2"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
psibase_macros = { version = "0.2.0", path = "../psibase_macros" }
psibase = { version = "0.2.0", path = "../psibase" }
serde = { version = "1", features = ["derive"] }
async-graphql = "4.0"

[profile.release]
debug = true