[package]
name = "example"
edition = "2021"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
license = "MIT"
publish = false

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
psibase_macros = { path = "../psibase_macros" }
psibase = { path = "../psibase" }
serde = { version = "1", features = ["derive"] }
async-graphql = "4.0"

[profile.release]
debug = true