[package]
name = "psibase_names"
version = "0.1.3"
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition = "2021"
description = "Psibase name conversion functions"
license = "MIT"

[dependencies]
seahash = "2.0.0"
