[package]
name = "psibase_names"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition = "2021"
description = "Psibase name conversion functions"
license = "MIT"

[dependencies]
seahash = "4.1.0"
rust-workspace-hack = { version = "0.1", path = "../rust-workspace-hack" }
