[package]
name = "psibase_names"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
description = "Psibase name conversion functions"
license.workspace = true
publish.workspace = true

[dependencies]
seahash = "4.1.0"
psibase-rust-workspace-hack.workspace = true
