[workspace]
resolver = "2"
members = ["plugin"]

[workspace.package]
version = "0.14.0"
rust-version = "1.64"
edition = "2021"
publish = false

[package]
name = "callee-pkg"           # Crate name
description = "plugin callee"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[package.metadata.psibase]
package-name = "Callee"

[package.metadata.psibase.dependencies]
HttpServer = "0.14.0"
Sites = "0.14.0"

[lib]
crate-type = ["rlib"]

[dependencies]
