package symbol-sys:plugin;

interface types {
    type account-number = string;
    type sym-id = string;
    type quantity = string;
}

interface symbol-sys {
    use types.{sym-id, quantity};

    create: func(symbol-name: string) -> result<_, string>;
    list-symbol: func(symbol-id: sym-id, price: quantity) -> result<_, string>;
    unlist-symbol: func(symbol-id: sym-id) -> result<_, string>;
    buy-symbol: func(symbol-id: sym-id) -> result<_, string>;
}


world psibase-plugin {
    export types;
    export symbol-sys;
}