[workspace]
resolver = "2"
members = ["service", "plugin"]

[workspace.package]
version = "0.21.0"
rust-version = "1.64"
edition = "2021"
publish = false

[package]
name = "auth-guild-pkg"            # Crate name
description = "Guild auth service"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[package.metadata.psibase]
package-name = "AuthGuild"
services = ["auth-guild"]

[package.metadata.psibase.dependencies]
HttpServer = "0.21.0"
Sites = "0.21.0"
Permissions = "0.21.0"

[lib]
crate-type = ["rlib"]

[dependencies]
auth-guild = { path = "service", version = "0.21.0" }
auth-guild-plugin = { path = "plugin", version = "0.21.0" }
