package chainmail:plugin;

interface types {
    record message {
        msg-id: u64,
        receiver: string,
        sender: string,
        subject: string,
        body: string,
        datetime: u32
    }
}

interface queries {
    use host:common/types.{error};
    use types.{message};

    get-msgs: func(sender: option<string>, receiver: option<string>) -> result<list<message>, error>;
    get-archived-msgs: func(sender: option<string>, receiver: option<string>) -> result<list<message>, error>;
}

interface api {
    use host:common/types.{error};

    // Send an email
    send: func(receiver: string, subject: string, body: string) -> result<_, error>;
    
    // Archive an email
    archive: func(msg-id: u64) -> result<_, error>;
    
    // Save an email
    save: func(event-id: u64) -> result<_, error>;
    
    // Unsave an email (remove it from state)
    unsave: func(event-id: u64) -> result<_, error>;
}

world imports {
    import api;
    import queries;
}