[package]
name = "psibase-macros-test"
edition = "2021"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true

# [lib]
# crate-type = ["cdylib"]

[dependencies]
psibase = { path = "../psibase" }
psibase_macros = { path = "../psibase_macros" }
async-graphql = "7.0.7"
serde = { version = "1.0.209", features = ["derive"] }
# colored-diff = "0.2.3"
# proc-macro2 = "1.0.36"
# syn = { version = "2.0.79" }
# quote = "1.0.15"
