[package]
name = "sites"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
async-graphql = "4.0"
fracpack = { version = "0.10.0", path = "../fracpack" }
psibase = { version = "0.10.0", path = "../psibase" }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0"
