package fractal:plugin;

interface council-types {
    enum petition-vote-type {
        approve,
        reject
    }
}

interface council {
    use fractal-types.{fractal-id, account, report-id};
    use council-types.{petition-vote-type};
    use social-types.{post-id};
    use common:plugin/types.{error};

    get-council-members: func(fractal-id: fractal-id) -> result<list<account>, error>;

    vote-petition: func(id: post-id, vote: petition-vote-type);
    appoint-ambassador: func(ambassador: account, to-fractal: account);

    resolve-report: func(id: report-id, resolution: string) -> result<_, error>;
}