package fractal:plugin;

interface identity-types {
    use fractal-types.{account};

    enum rating {
        confident-not-who-they-claim,
        likely-not-who-they-claim,
        likely-who-they-claim,
        confident-who-they-claim,
    }

    record identity-attestation {
        rater: account,
        rating: rating,
        datetime: string,
    }
    
    record identity-summary {
        total-attestations: u16,
        total-attesters: u16,
        perc-confident: u8,
        perc-likely: u8,
        perc-likely-not: u8,
        perc-confident-not: u8,
        avg-score: float32, // ?
    }
}

interface identity {
    use fractal-types.{account};
    use fractal:plugin/social-types.{rating};

    attest: func(to: account, rating: rating);
    get-identity-stats: func(account: account);
}
