package fractal:plugin;

interface parameters {
    type members-per-slate-max = u8;
    type members-per-slate-min = u8;
    type number-rounds-max = u8;

    get-parameters: func();
    get-parameter: func(param-name: string);
}

interface types {
    use accounts:plugin/types.{account};
    use common:plugin/types.{error};

    type fractal-id = account;
    type report-id = u64;
    type invite-id = u64;

    record ambassador-relationship {
        ambassador: account,
        to-fractal: account,
    }

    record fractal-profile {
        account: account,
        founder: account,
        name: string,
        description: string,
        region: string,
        language-code: string,
        meeting-frequency: string,
        meeting-datetime: string,
        ambassadors: list<ambassador-relationship>,
    }

    record fractal {
        fractal-profile: fractal-profile,
        members: list<account>,
        member-fractals: list<account>,
    }

    enum evaluation-type {
        member-contribution,
        delegate,
        member-fractal-contribution,
        member-fractal-delegate,
    }

    record meeting-info {
        room-url: string,
        schedule: schedule,
        members: list<account>,
    }

    record fractal-params {
        // all configurable fractal params
    }

    record schedule {
        evalution-start-datetime: string,
        evalution-end-datetime: string,
        sync-up-start-datetime: string,
        sync-up-duration-minutes: u16,
    }

    record fractal-creation-info {
        name: string,
        description: string,
        member-schedule: schedule,
        delegate-schedule: schedule,
        member-fractal-schedule: schedule,
        fractal-delegate-schedule: schedule,
        language: string,
        region: string,
    }
    
    record profile-details-update {
        name: string,
        description: string,
    }

    enum digital-property {
        reputation,
        favor,
        fractal-repuation,
        fractal-favor,
    }

    record digital-property-stat {
        digital-property: digital-property,
        average: float32,
        recent-history: list<float32>,
    }

    record attendance-stats {
        all-time-attendance-perc: u8,
        recent-average: float32,
        recent-history: list<bool>,
    }

    use attestation:plugin/types.{summary};

    type member-stats = list<digital-property-stat>;
    record public-profile {
        account: account,
        name: string,
        description: string,
        identity-summary: summary,
        is-delegate: bool,
        member-stats: member-stats,
        attendance: attendance-stats,
        fractal-membership: list<fractal>,
    }
    record profile-flags {
        registered-member-eval: bool,
        registered-member-fractal: bool,
        registered-delegate-eval: bool,
        registered-member-delegate-eval: bool,
        willing-ambassador: bool,
        willing-ambassador-fractals: list<fractal>,
    }

    record tokenomic-pool {
        name: string,
        perc-of-emission: float32,
    }

    record tokenomic-params {
        emission-rate-annual: float32,
        pools: list<tokenomic-pool>,
    }
}

interface api {
    use common:plugin/types.{error};
    use accounts:plugin/types.{account};
    use types.{fractal-id, fractal-params, fractal-creation-info, report-id, public-profile, profile-details-update, meeting-info, tokenomic-params, profile-flags, evaluation-type, invite-id};
    // get-ambassador: func(for-fractal: account);

    // Called by: Fractal founder/admin
    create: func(fractal-details: fractal-creation-info) -> result<fractal-id, error>;

    // Called by: Non-members
    apply-for-membership: func(fractal-id: fractal-id);
    
    // member joining fractal
    accept-invite-with-new-account: func(id: invite-id, account-name: string) -> result<account, error>;
    accept-invite-with-existing-account: func(id: invite-id) -> result<_, error>;
    reject-invite: func(id: invite-id) -> result<_, error>;

    // Called by: Member
    invite: func(fractal-id: fractal-id) -> result<invite-id, error>;
    // profile
    update-member-properties: func(fractal-id: fractal-id, details: profile-details-update) -> result<_, error>;

    // rpc REST calls
    get-my-profile: func(fractal-id: fractal-id) -> result<public-profile, error>;
    get-profiles: func(fractal-id: fractal-id, members: list<account>) -> result<list<public-profile>, error>;
}

world fractal-plugin {
    export types;
    export api;
}