[package]
name = "branding-pkg"
description = "Allow operators to rebrand their network easily"
version = "0.19.0"
rust-version = "1.64"
edition = "2021"
publish = false


[package.metadata.psibase]
package-name = "Branding"
services = ["branding"]

[package.metadata.psibase.dependencies]
HttpServer = "0.19.0"
Sites = "0.19.0"

[lib]
crate-type = ["rlib"]

[dependencies]
branding = { path = "service", version = "0.19.0" }
branding-plugin = { path = "plugin", version = "0.19.0" }
