[workspace]
resolver = "2"
members = ["service", "plugin"]

[workspace.package]
version = "0.14.0"
rust-version = "1.64"
edition = "2021"
publish = false
repository = "https://github.com/gofractally/psibase"
homepage = "https://psibase.io"

[package]
name = "branding-pkg"
description = "Allow operators to rebrand their network easily"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[package.metadata.psibase]
package-name = "Branding"
services = ["branding"]

[package.metadata.psibase.dependencies]
HttpServer = "0.14.0"
Sites = "0.14.0"

[lib]
crate-type = ["rlib"]

[dependencies]
branding = { path = "service", version = "0.14.0" }
plugin = { path = "plugin", version = "0.14.0" }
