# [workspace]

[package]
name = "branding_package"
# version = "0.1.0"
# rust-version = "1.79.0"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition = "2021"
publish = false

[package.metadata.psibase]
package-name = "branding"
description = "Allow operators to rebrand their network easily"
services = ["branding"]
flags = []
# server = "branding"
# plugin = "branding-plugin"

[lib]
crate-type = ["rlib"]

# [package.metadata.psibase.dependencies]
# branding = { path = "service" }
# HttpServer = "0.12.0"

[dependencies]
branding = { path = "service", version = "0.1.0" }
