[package]
name = "branding_package"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition = "2021"
publish = false

[package.metadata.psibase]
package-name = "branding"
description = "Allow operators to rebrand their network easily"
services = ["branding"]

[lib]
crate-type = ["rlib"]

[dependencies]
branding = { path = "service" }
plugin = { path = "plugin" }
