[package]
name = "r-evaluations"
description = "RPC service for evaluations"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
psibase = { path = "../../../../rust/psibase/", version = "0.17.0" }
serde = "1.0"
serde_json = "1.0"
evaluations = { path = "../service", version = "0.17.0" }
async-graphql = "=7.0.17"
serde-aux = "4.7.0"
