[package]
name = "gen-cpp-doc"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
publish = false
description = "Generate C++ documentation; supports the psibase repo only"
license.workspace = true

[dependencies]
anyhow.workspace = true
clang = { version = "1", features = ["clang_10_0"] }
clap.workspace = true
mdbook = "0.4"
pulldown-cmark = "0.9"
regex.workspace = true
serde_json.workspace = true
svgbob = "0.6"
psibase-rust-workspace-hack.workspace = true
