[package]
name = "gen-cpp-doc"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition = "2021"
publish = false
description = "Generate C++ documentation; supports the psibase repo only"

[dependencies]
anyhow = "1.0"
clang = {version = "1", features = ["clang_10_0"]}
clap = {version = "3.1", features = ["derive"]}
mdbook = "0.4"
pulldown-cmark = "0.9"
regex = "1"
serde_json = "1.0"
svgbob = "0.6"
