[package]
name = "r-symbol"
description = "RPC service for symbol"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
psibase = { path = "../../../../rust/psibase/", version = "0.19.0" }
serde = "1.0"
serde_json = "1.0"
symbol = { path = "../service", version = "0.19.0" }
async-graphql = { version = "7.0.10" }
