[package]
name = "r-staged-tx"
description = "Query service for staged transaction service"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition = "2021"
publish = false

[dependencies]
psibase.workspace = true
serde.workspace = true
serde_json.workspace = true
staged-tx = { path = "../service", version = "0.21.0" }
async-graphql.workspace = true
system-workspace-hack = { version = "0.1", path = "../../system-workspace-hack" }
