[package]
name = "r-staged-tx"
description = "Query service for staged transaction service"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition = "2021"
publish = false

[dependencies]
psibase = { path = "../../../../rust/psibase/", version = "0.21.0" }
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.120"
staged-tx = { path = "../service", version = "0.21.0" }
async-graphql = "=7.0.17"
