[package]
name = "r-staged-tx"
description = "Query service for staged transaction service"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
publish = false

[dependencies]
psibase.workspace = true
serde.workspace = true
serde_json.workspace = true
staged-tx = { path = "../service", version = "0.22.0" }
async-graphql.workspace = true
psibase-system-workspace-hack.workspace = true
