[package]
name = "component-parser"
version = "0.19.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
wasm-compose = "0.224.0"
wasmparser = "0.224.0"
wit-component = "0.224.0"
wit-bindgen-rt = { version = "0.39.0", features = ["bitflags"] }
wit-parser = "0.224.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
indexmap = "2.2.5"

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:component-parser"

[package.metadata.component.bindings]
derives = ["serde::Serialize", "serde::Deserialize"]
