[package]
name = "fractals-pkg"
description = "Fractal governance"
version = "0.19.0"
rust-version = "1.64"
edition = "2021"
publish = false


[package.metadata.psibase]
package-name = "Fractals"
services = ["fractals"]

[package.metadata.psibase.dependencies]
HttpServer = "0.19.0"
Sites = "0.19.0"

[lib]
crate-type = ["rlib"]

[dependencies]
r-fractals = { path = "query-service", version = "0.17.0" }
fractals-plugin = { path = "plugin", version = "0.17.0" }
fractals = { path = "service", version = "0.19.0" }
r-fractals = { path = "query-service", version = "0.19.0" }
plugin = { path = "plugin", version = "0.19.0" }
