pub const CANDIDATE_TITLE_BIT_OFFSET: u32 = 0;
pub const COUNCIL_SIZE: u8 = 12;
pub const DURATION_REGISTRATION_MINUTES: i64 = 2;
pub const DURATION_DELIBERATION_MINUTES: i64 = 55;
pub const DURATION_SUBMISSION_MINUTES: i64 = 3;
