[package]
name = "subgroups"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
psibase = { version = "0.16.0", path = "../../../../rust/psibase" }
psibase_macros = { version = "0.16.0", path = "../../../../rust/psibase_macros" }
serde = { version = "1.0.208", features = ["derive"] }

[dev-dependencies]
subgroups-pkg = { path = "..", version = "0.16.0" }
