[package]
name = "subgroups"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
psibase = { version = "0.15.0", path = "../../../../rust/psibase" }
psibase_macros = { version = "0.15.0", path = "../../../../rust/psibase_macros" }
async-graphql = "7.0.7"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.120"

[dev-dependencies]
subgroups-pkg = { path = "..", version = "0.15.0" }
