[package]
name = "r-diff-adjust"
description = "RPC service for diff-adjust"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
psibase = { path = "../../../../rust/psibase/", version = "0.21.0" }
serde = "1.0"
serde_json = "1.0"
diff-adjust = { path = "../service", version = "0.21.0" }
async-graphql = { version = "7.0.10" }
