[package]
name = "r-diff-adjust"
description = "RPC service for diff-adjust"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
psibase.workspace = true
serde.workspace = true
serde_json.workspace = true
diff-adjust = { path = "../service", version = "0.22.0" }
async-graphql.workspace = true