global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: "psinode_logs"
    scrape_interval: 1s
    static_configs:
      - targets: ["exporters:9144"]

  - job_name: "psinode_perf"
    scrape_interval: 1s
    metrics_path: /native/admin/metrics
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  # - job_name: "node"
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ["localhost:8085"]
