[package]
name = "token-stream-pkg"
description = "Stream tokens by exponential decay"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "TokenStream"
services = ["token-stream"]

[package.metadata.psibase.dependencies]
HttpServer = "0.21.0"
Sites = "0.21.0"
Tokens = "0.21.0"


[lib]
crate-type = ["rlib"]

[dependencies]
token-stream = { path = "service", version = "0.21.0" }
r-token-stream = { path = "query-service", version = "0.21.0" }
token-stream-plugin = { path = "plugin", version = "0.21.0" }
