[workspace]
resolver = "2"
members = ["service", "plugin", "query-service"]

[workspace.package]
version = "0.20.0"
rust-version = "1.64"
edition = "2021"
publish = false

[package]
name = "difficulty-pkg"
description = "General purpose Bitcoin inspired difficulty package"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[package.metadata.psibase]
package-name = "Difficulty"
services = ["difficulty"]

[package.metadata.psibase.dependencies]
HttpServer = "0.20.0"
Sites = "0.20.0"
Permissions = "0.20.0"

[lib]
crate-type = ["rlib"]

[dependencies]
difficulty = { path = "service", version = "0.20.0" }
r-difficulty = { path = "query-service", version = "0.20.0" }
difficulty-plugin = { path = "plugin", version = "0.20.0" }
