[workspace]
resolver = "2"
members = ["service", "plugin"]

[workspace.package]
version = "0.21.0"
rust-version = "1.64"
edition = "2021"
publish = false

[package]
name = "fractal-core-pkg"                      # Crate name
description = "Individual fractal deployment"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[package.metadata.psibase]
package-name = "FractalCore"
services = ["fractal-core"]

[package.metadata.psibase.dependencies]
HttpServer = "0.21.0"
Sites = "0.21.0"
Permissions = "0.21.0"

[lib]
crate-type = ["rlib"]

[dependencies]
fractal-core = { path = "service", version = "0.21.0" }
r-fractal-core = { path = "query-service", version = "0.21.0" }
fractal-core-plugin = { path = "plugin", version = "0.21.0" }
