package webmail:plugin;

interface types {
    record message {
        receiver: string,
        sender: string,
        subject: string,
        content: string,
    }
}

interface queries {
    use types.{message};
    use host:common/types.{error};

    get-messages: func(sender: string, receiver: string) -> result<list<message>, error>;
}

interface api {
    use host:common/types.{error};

    // Send an email
    send: func(receiver: string, subject: string, body: string) -> result<_, error>;
}

world imports {
    import queries;
    import api;
}