---
modules:
  default:
    metrics:
      # Transactions
      - name: psinode_transactions_total
        path: "{ .transactions.total }"
        help: Total number of transactions
      - name: psinode_transactions_unprocessed
        path: "{ .transactions.unprocessed }"
        help: Unprocessed transactions
      - name: psinode_transactions_failed
        path: "{ .transactions.failed }"
        help: Failed transactions
      - name: psinode_transactions_succeeded
        path: "{ .transactions.succeeded }"
        help: Succeeded transactions
      - name: psinode_transactions_skipped
        path: "{ .transactions.skipped }"
        help: Skipped transactions

      # Memory
      - name: psinode_memory_database
        valuetype: gauge
        path: "{ .memory.database }"
        help: Memory database
      - name: psinode_memory_code
        valuetype: gauge
        path: "{ .memory.code }"
        help: Memory code
      - name: psinode_memory_data
        valuetype: gauge
        path: "{ .memory.data }"
        help: Memory data
      - name: psinode_memory_wasm_memory
        valuetype: gauge
        path: "{ .memory.wasmMemory }"
        help: Memory wasm memory
      - name: psinode_memory_wasm_code
        valuetype: gauge
        path: "{ .memory.wasmCode }"
        help: Memory wasm code
      - name: psinode_memory_unclassified
        valuetype: gauge
        path: "{ .memory.unclassified }"
        help: Memory unclassified

      # Tasks Threads
      - name: psinode_tasks
        type: object
        help: Tasks
        path: "{ .tasks[*] }"
        labels:
          id: "{ .id }"
          group: "{ .group }"
        values:
          user: "{ .user }"
          system: "{ .system }"
          page_faults: "{ .pageFaults }"
          read: "{ .read }"
          written: "{ .written }"
