[package]
name = "webmail"
version = "0.1.0"
edition = "2021"

[dependencies]
psibase = { path = "../../../../rust/psibase/" }
async-graphql = "7.0.7"
serde = { version = "1.0.209", features = ["derive"] }
