[package]
name = "tokens-pkg"                   # Crate name
description = "Native tokens service"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "Tokens"
services = ["tokens"]

[package.metadata.psibase.dependencies]
HttpServer = "0.22.0"
Sites = "0.22.0"

[lib]
crate-type = ["rlib"]

[dependencies]
tokens = { path = "service", version = "0.22.0" }
r-tokens = { path = "query-service", version = "0.22.0" }
tokens-plugin = { path = "plugin", version = "0.22.0" }
psibase-user-workspace-hack.workspace = true
