[package]
name = "tokens-pkg"                   # Crate name
description = "Native tokens service"
version = "0.21.1"
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "Tokens"
services = ["tokens"]

[package.metadata.psibase.dependencies]
HttpServer = "0.21.0"
Sites = "0.21.0"

[lib]
crate-type = ["rlib"]

[dependencies]
tokens = { path = "service", version = "0.21.1" }
r-tokens = { path = "query-service", version = "0.21.1" }
tokens-plugin = { path = "plugin", version = "0.21.1" }
