package brotli-codec:plugin;

interface api {
    use host:common/types.{error};

    /// Compress content using Brotli.
    ///
    /// Parameters:
    ///  * `content` - The content being compressed
    ///  * `quality` - Ranges from 1-11, where 1 is the fastest, and 11 is the best
    ///                compression
    compress: func(content: list<u8>, quality: u8) -> result<list<u8>, error>;

    /// Decompress brotli-compressed content
    /// 
    /// Parameters:
    ///  * `content` - The brotli-compressed content
    decompress: func(content: list<u8>) -> list<u8>;
}

world imports {
    import api;
}