package component:demoapp2;

interface types {
    record funccallparams {
        service: string,
        method: string,
        params: string
    }
}

interface imports {
    use types.{funccallparams};

    get-logged-in-user: func() -> string;
    add-to-tx: func(msg: funccallparams);
 }


/// An example world for the component to target.
world example {
    import imports;
    export derpy: func() -> string;
}
