package accounts:plugin;

world impl {
    include host:common/imports;
    include host:privileged/imports;
    include clientdata:plugin/imports;
    include transact:plugin/imports;

    export accounts;
}
