[package]
name = "profiles-pkg"
description = "Add profiles"
version = "0.17.0"
rust-version = "1.64"
edition = "2021"
publish = false


[package.metadata.psibase]
package-name = "Profiles"
services = ["profiles"]

[package.metadata.psibase.dependencies]
HttpServer = "0.17.0"
Sites = "0.17.0"

[lib]
crate-type = ["rlib"]

[dependencies]
profiles = { path = "service", version = "0.17.0" }
r-profiles = { path = "query-service", version = "0.17.0" }
profiles-plugin = { path = "plugin", version = "0.17.0" }
