[package]
name = "evaluations"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.psibase]
server = "r-evaluations"
plugin = "evaluations-plugin"
data = [{ src = "../ui/dist", dst = "/" }]
postinstall = [
    # { sender = "evaluations", service = "evaluations", method = "init", rawData = "0000" },
    { sender = "evaluations", service = "sites", method = "enablespa", rawData = "010001" },
]

[dependencies]
psibase.workspace = true
async-graphql.workspace = true
serde.workspace = true
serde_json.workspace = true
rand = "0.9.1"
ecies = { version = "0.2", default-features = false, features = ["pure"] }
average = "0.16.0"
serde-aux.workspace = true
user-workspace-hack = { version = "0.1", path = "../../user-workspace-hack" }

[dev-dependencies]
