[package]
name = "evaluations"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.psibase]
server = "r-evaluations"
plugin = "plugin"
data = [{ src = "../ui/dist", dst = "/" }]
postinstall = [
    # { sender = "evaluations", service = "evaluations", method = "init", rawData = "0000" },
    { sender = "evaluations", service = "sites", method = "enablespa", rawData = "010001" },
]

[dependencies]
psibase = { version = "0.20.0", path = "../../../../rust/psibase" }
async-graphql = "=7.0.17"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.120"
rand = "0.9.1"
ecies = { version = "0.2", default-features = false, features = ["pure"] }
average = "0.16.0"

[dev-dependencies]
