[package]
name = "fractals"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.psibase]
server = "r-fractals"
plugin = "plugin"
data = [{ src = "../ui/dist", dst = "/" }]
postinstall = [
    { sender = "fractals", service = "sites", method = "enablespa", rawData = "010001" },
]


[dependencies]
psibase = { version = "0.18.0", path = "../../../../rust/psibase" }
psibase_macros = { version = "0.18.0", path = "../../../../rust/psibase_macros" }
evaluations = { path = "../../Evaluations/service", version = "0.18.0" }
async-graphql = "7.0.7"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.120"

[dev-dependencies]
fractals-pkg = { path = "..", version = "0.18.0" }
