[package]
name = "app-registry"
description = "App Registry Service"
edition = "2021"
version = "0.1.0"

[package.metadata.psibase]
server = "r-tpack"

[package.metadata.psibase.dependencies]
HttpServer = "0.12.0"

# [lib]
# path = "src/lib.rs"
# crate-type = ["cdylib"]

[dependencies]
psibase = { path = "../../../../rust/psibase" }
serde = { version = "1", features = ["derive"] }
async-graphql = "7.0.7"
serde_json = "1.0.120"

[dev-dependencies]
app_registry_package = { path = "..", version = "0.1.0" }
