[workspace]
resolver = "2"
members = ["service"]

[workspace.package]
version = "0.20.0"
rust-version = "1.64"
edition = "2021"
publish = false

[package]
name = "subgroups-pkg"
description = "Generates subgroups given total population and allowed group size"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[package.metadata.psibase]
package-name = "Subgroups"
services = ["subgroups"]

[lib]
crate-type = ["rlib"]

[dependencies]
subgroups = { path = "service", version = "0.20.0" }
