[package]
name = "subgroups-pkg"
description = "Generates subgroups given total population and allowed group size"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "Subgroups"
services = ["subgroups"]

[lib]
crate-type = ["rlib"]

[dependencies]
subgroups = { path = "service", version = "0.22.0" }
user-workspace-hack = { version = "0.1", path = "../user-workspace-hack" }
