[package]
name = "mincallrecvr"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[package.metadata.psibase]
package-name = "mincallrecvr"

[package.metadata.psibase.dependencies]
HttpServer = "0.21.0"

[dependencies]
psibase.workspace = true
psibase_macros.workspace = true
async-graphql.workspace = true
serde.workspace = true
psibase-rust-workspace-hack.workspace = true

[dev-dependencies]
psimacrotest = { path = "../.." }
