yarnPath: .yarn/releases/yarn-4.9.1.cjs

nodeLinker: pnp

enableGlobalCache: true
cacheFolder: /root/psibase/services/.yarn/cache
enableMirror: true

packageExtensions:
  typescript@*:
    dependencies:
      react: ^18.2.0
      react-dom: ^18.2.0
      rollup: ^4.40.0
      typescript: ^5.7.3
