# Choose one of these nodeLinker options:
# - pnp: More secure but requires compatible tools
# - node-modules: More compatible with older tools
nodeLinker: pnp

# Specify the Yarn version to use
yarnPath: .yarn/releases/yarn-4.9.1.cjs

# Package extensions to enforce consistent versions
packageExtensions:
  typescript@*:
    dependencies:
      typescript: ^5.7.3
      rollup: ^4.40.0
      react: ^18.2.0
      react-dom: ^18.2.0

# Cache settings
enableGlobalCache: true
cacheFolder: /root/psibase/services/.yarn/cache
enableMirror: true

# Optional: Uncomment to use PnP instead of node-modules
# pnpMode: loose  # Use 'loose' for better compatibility
# pnpFallbackMode: all
