cacheFolder: /root/psibase/services/.yarn/cache

enableGlobalCache: true

enableMirror: true

nodeLinker: pnp

packageExtensions:
  typescript@*:
    dependencies:
      react: ^18.2.0
      react-dom: ^18.2.0
      rollup: ^4.40.0
      typescript: ^5.7.3
