[workspace]
resolver = "2"
# each proj must be listed (can't combine via a cargo.toml
# `user/Branding` didn't need to be referenced
members = ["user/Branding/service", "user/Branding/plugin"]

#Package names of component projects
default-members = ["branding", "plugin"]

[workspace.package]
version = "0.12.0"
rust-version = "1.64"
repository = "https://github.com/gofractally/psibase"
homepage = "https://psibase.io"

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true
