[package]
name = "chainmail"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[package.metadata.psibase]
server = "r-chainmail"
plugin = "plugin"
data = [{ src = "../ui/dist/", dst = "/" }]
postinstall = [{ sender = "chainmail", service = "chainmail", method = "init" }]

[dependencies]
psibase = { path = "../../../../rust/psibase/", version = "0.16.0" }
async-graphql = "7.0.7"
serde = { version = "1.0.209", features = ["derive"] }
sha2 = { version = "0.10.0" }

[dev-dependencies]
chainmail-pkg = { path = "..", version = "0.16.0" }
