[package]
name = "chainmail"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
publish = false

[package.metadata.psibase]
server = "chainmail"
plugin = "plugin"
data = [{ src = "../ui/dist/", dst = "/" }]
postinstall = [{ sender = "chainmail", service = "chainmail", method = "init" }]

[dependencies]
psibase = { path = "../../../../rust/psibase/", version = "0.17.0" }
async-graphql = "=7.0.17"
serde = { version = "1.0.209", features = ["derive"] }

[dev-dependencies]
chainmail_package = { path = "..", version = "0.17.0" }
