# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["peter@huene.dev"]
description = "WebAssembly component builder"
language = "rust"
manifest_version = 2
name = "wasmbuilder.app"

[scripts]
  build = "cargo build --bin fastly-compute-project --release --target wasm32-wasi --color always"
