package clientdata:plugin;

interface tests {
    use host:common/types.{error};
    kv-test: func() -> result<_, error>;
}

world impl {
    include host:common/imports;

    export keyvalue;
    export tests;
}