package clientdata:plugin;

interface tests {
    use host:common/types.{error};
    kv-test-step1: func() -> result<_, error>;
    kv-test-step2: func() -> result<_, error>;
    kv-test-step3-shouldfail: func() -> result<_, error>;
    kv-test-step4: func() -> result<_, error>;
}

world impl {
    include host:common/imports;
    include setcode:plugin/imports;
    include chainmail:plugin/imports;

    export keyvalue;
    export tests;
}