[package]
name = "profiles"             # Crate name
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.psibase]
server = "r-profiles"
plugin = "profiles-plugin"

[dependencies]
psibase.workspace = true
psibase_macros.workspace = true
async-graphql.workspace = true
serde.workspace = true
serde_json.workspace = true
user-workspace-hack = { version = "0.1", path = "../../user-workspace-hack" }

[dev-dependencies]
profiles-pkg = { path = "..", version = "0.22.0" }
