[package]
name = "profiles"             # Crate name
version = "0.21.1"
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.psibase]
server = "r-profiles"
plugin = "profiles-plugin"

[dependencies]
psibase.workspace = true
psibase_macros.workspace = true
async-graphql.workspace = true
serde.workspace = true
serde_json.workspace = true
psibase-user-workspace-hack.workspace = true

[dev-dependencies]
profiles-pkg = { path = "..", version = "0.21.1" }
