[package]
name = "r-evaluations"
description = "RPC service for evaluations"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
psibase.workspace = true
serde.workspace = true
serde_json.workspace = true
evaluations = { path = "../service", version = "0.21.0" }
async-graphql.workspace = true
serde-aux.workspace = true
ecies = { version = "0.2", default-features = false, features = ["pure"] }
average = "0.16.0"
psibase-user-workspace-hack.workspace = true
