[package]
name = "auth-invite"
version = "0.12.0"
edition = "2021"

[dependencies]
wit-bindgen-rt = { version = "0.33.0", features = ["bitflags"] }
psibase = { path = "../../../../rust/psibase/" }

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[package.metadata.component.target]
world = "impl"

[package.metadata.component]
package = "auth-invite:plugin"

[package.metadata.component.target.dependencies]
"host:common" = { path = "../../CommonApi/common/packages/wit/host-common.wit" }
"invite:plugin" = { path = "../../Invite/plugin/wit/world.wit" }
"clientdata:plugin" = { path = "../../ClientData/plugin/wit/world.wit" }
"accounts:smart-auth" = { path = "../../../system/Accounts/plugin/smartAuth/world.wit" }
"auth-sig:plugin" = { path = "../../../system/AuthSig/plugin/wit/world.wit" }
"transact:plugin" = { path = "../../../system/Transact/plugin/wit/world.wit" }
