[package]
name = "auth-invite"
version.workspace = true
edition.workspace = true

[dependencies]
wit-bindgen-rt = { version = "0.33.0", features = ["bitflags"] }
psibase = { path = "../../../../rust/psibase/" }

[lib]
crate-type = ["cdylib"]

[package.metadata.component.target]
world = "impl"

[package.metadata.component]
package = "auth-invite:plugin"

[package.metadata.component.target.dependencies]
"host:common" = { path = "../../CommonApi/common/packages/wit/host-common.wit" }
"invite:plugin" = { path = "../../Invite/plugin/wit/world.wit" }
"clientdata:plugin" = { path = "../../ClientData/plugin/wit/world.wit" }
"accounts:smart-auth" = { path = "../../../system/Accounts/plugin/smartAuth/export.wit" }
"auth-sig:plugin" = { path = "../../../system/AuthSig/plugin/wit/world.wit" }
"transact:plugin" = { path = "../../../system/Transact/plugin/wit/world.wit" }
