package transact:plugin;


/// Interface used by auth notifiers.
/// Auth notifiers are plugins that add additional claims/proofs to transactions
///   without being the user's specified auth service plugin.
interface auth-notifier {
    /// Notifies the transact plugin that the caller plugin has one or more claims/proofs to add to the 
    /// transaction.
    notify: func();
}

interface intf {
    use host:common/types.{error};

    /// Adds the specified service action to the current transaction.
    /// 
    /// No service is specified, as it is only possible for a plugin to call an
    /// action on its own service. To call actions on another service, it must use
    /// that service's plugin.
    /// 
    /// Parameters
    /// * `method-name`: The method name of the action being called
    /// * `packed-args`: The arguments for the action, packed into fracpack format
    add-action-to-transaction: func(method-name: string, packed-args: list<u8>) -> result<_, error>;
}

world imports {
    import intf;
}
