[package]
name = "test_package"
description = "Test for package building"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "TestPackage"
services = ["tpack"]

[lib]
crate-type = ["rlib"]

[dependencies]
tpack = { path = "service", version = "0.21.0" }
r-tpack = { path = "query", version = "0.21.0" }
psibase-rust-workspace-hack.workspace = true
