[package]
name = "test_package"
version = "0.12.0"

[package.metadata.psibase]
package-name = "TestPackage"
description = "Test for package building"
services = ["tpack"]

[dependencies]
tpack = { path = "service", version = "0.12.0" }
r-tpack = { path = "query", version = "0.12.0" }
