package attestation:plugin;

interface api {
    use common:plugin/types.{error};

    /* store the tuple<calling service as namespace, attestation-type> with payload
      - `claim` - a JSON string
        - (for the identity service, the entity being attested to and the normalized float, i.e., 0.0-1.0 representing the confidence of the identity
    */
    // Simple call that builds the VC, making assumptions about who's the holder, the subject, etc.
    // assumption: subject == holder
    // `claim` maps to `credential-subject` in the VC
    attest: func(attestation-type: string, claim: string) -> result<_, error>;
    // build a VC and pass that to the server
}

world attestation-world {
    import common:plugin/server;
    export api;
}