[package]
name = "psimacrotest"
edition = "2021"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
crate-type = ["rlib"]

[package.metadata.psibase]
# Relates to test cases specification of packages that should be loaded on the chain
package-name = "PsiMacroTest"
# services installed by the package
services = ["basicwquery", "mincallrecvr", "addcheckinit"]

[dependencies]
psibase = { path = "../psibase" }
psibase_macros = { path = "../psibase_macros" }
async-graphql.workspace = true
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.132"
basicwquery = { path = "services/basic-w-query" }
mincallrecvr = { path = "services/min-call-recvr" }
addcheckinit = { path = "services/add-check-init" }
