[package]
name = "psimacrotest"
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[lib]
crate-type = ["rlib"]

[package.metadata.psibase]
# Relates to test cases specification of packages that should be loaded on the chain
package-name = "PsiMacroTest"
# services installed by the package
services = ["basicwquery", "mincallrecvr", "addcheckinit"]

[dependencies]
psibase.workspace = true
psibase_macros.workspace = true
async-graphql.workspace = true
serde = { version = "1.0.209", features = ["derive"] }
serde_json.workspace = true
basicwquery = { path = "services/basic-w-query" }
mincallrecvr = { path = "services/min-call-recvr" }
addcheckinit = { path = "services/add-check-init" }
psibase-rust-workspace-hack.workspace = true
