[package]
name = "diff-adjust-pkg"                               # Crate name
description = "Bitcoin inspired difficulty adjustment"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "DiffAdjust"
services = ["diff-adjust"]

[package.metadata.psibase.dependencies]
HttpServer = "0.22.0"
Sites = "0.22.0"

[lib]
crate-type = ["rlib"]

[dependencies]
diff-adjust = { path = "service", version = "0.22.0" }
r-diff-adjust = { path = "query-service", version = "0.22.0" }
psibase-user-workspace-hack.workspace = true
