package {{project-name}}:plugin;

interface api {
    set-example-thing: func(thing: string);
}

interface queries {
    use host:common/types.{error};
    get-example-thing: func() -> result<string, error>;
}

world psibase-plugin {
    import host:common/server;
    import transact:plugin/intf;
    include sites:plugin/imports;

    export api;
    export queries;
}
