[package]
name = "identity"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.psibase]
plugin = "identity-plugin"
data = [{ src = "../ui/dist", dst = "/" }]

[dependencies]
psibase_macros.workspace = true
psibase.workspace = true
serde.workspace = true
async-graphql.workspace = true
serde_json.workspace = true
psibase-user-workspace-hack.workspace = true

[dev-dependencies]
identity-pkg = { path = "..", version = "0.22.0" }
