[package]
name = "branding"
version = "0.21.1"
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
publish = false

[package.metadata.psibase]
server = "branding"
plugin = "plugin"
data = [{ src = "../ui/dist", dst = "/" }]

[dependencies]
psibase.workspace = true
psibase_macros.workspace = true
async-graphql.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
branding-pkg = { path = "..", version = "0.21.1" }
