[package]
name = "branding"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
publish = false

[package.metadata.psibase]
server = "branding"
plugin = "branding-plugin"
data = [{ src = "../ui/dist", dst = "/" }]

[dependencies]
psibase.workspace = true
psibase_macros.workspace = true
async-graphql.workspace = true
serde.workspace = true
serde_json.workspace = true
user-workspace-hack = { version = "0.1", path = "../../user-workspace-hack" }

[dev-dependencies]
branding-pkg = { path = "..", version = "0.22.0" }
