package evaluations:plugin;


interface types {

    type account = string;



}

interface api {
    use host:common/types.{error};
    use types.{account};
    

    create: func(registration: u32, deliberation: u32, submission: u32, finish-by: u32, allowable-group-sizes: list<string>) -> result<_, error>;

    register: func(id: u32, account: account) -> result<_, error>;
    unregister: func(id: u32) -> result<_, error>;

    start: func(id: u32, entropy: u64) -> result<_, error>;

    barry: func() -> result<_, error>;


    close: func(evaluation-id: u32) -> result<_, error>;

    attest: func(evaluation-id: u32, submission: list<u8>) -> result<_, error>;
    propose: func(evaluation-id: u32, group-number: u32, proposal: list<string>) -> result<string, error>;

    refresh-key: func(key: list<u8>) -> result<_, error>;
   
}


world imports {
    import api;
}
