package component:tokens;



interface types {

    type quantity = string;
    type precision = u8;
    type token-id = string;
    type token-number = u32;
    type account-number = string;

    record token-detail {
        id: token-number,
        owner: string,
        precision: u8,
        symbol-id: string,
    }

    record balance {
        balance: string,
        creditor: string,
        debitor: string,
        token-number: token-number,
    }
}



interface intf {
    use common:plugin/types.{error};
    use types.{precision, quantity, token-id, account-number};
    
    create: func(a: precision, b: quantity) -> result<_, error>;
    burn: func(code: token-id, amount: quantity, memo: string, account: account-number) -> result<_, error>;
    mint: func(code: token-id, amount: quantity, memo: string) -> result<_, error>;
}

interface transfer {
    use common:plugin/types.{error};
    use types.{token-id, account-number, quantity, balance, token-detail};

    token-owner: func(code: token-id) -> result<token-detail, error>;
    uncredit: func(code: token-id, debitor: account-number, amount: quantity, memo: string) -> result<_, error>;
    credit: func(code: token-id, receiver: account-number, amount: quantity, memo: string) -> result<_, error>;
}

/// An example world for the component to target.
world example {

    import common:plugin/server;
    import common:plugin/client;



    export types;
    export intf;
    export transfer;
}