[package]
name = "credentials"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.psibase]
plugin = "credentials-plugin"
postinstall = [
    { sender = "credentials", service = "credentials", method = "init", data = {} },
    { sender = "accounts", service = "accounts", method = "newAccount", data = { name = "cred-sys", authService = "credentials", requireNew = false } },
]

[dependencies]
psibase.workspace = true
psibase_macros.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
credentials-pkg = { path = "..", version = "0.21.0" }
