[workspace]
resolver = "2"
members = ["service", "plugin", "query-service"]

[workspace.package]
version = "0.19.0"
rust-version = "1.64"
edition = "2021"
publish = false

[package]
name = "evaluations-pkg"                                                                                          # Crate name
description = "Facilitates the discovery of one or more groups' rank-ordered preferences over a list of elements"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[package.metadata.psibase]
package-name = "Evaluations"
services = ["evaluations"]

[package.metadata.psibase.dependencies]
HttpServer = "0.19.0"
Sites = "0.19.0"

[lib]
crate-type = ["rlib"]

[dependencies]
evaluations = { path = "service", version = "0.19.0" }
r-evaluations = { path = "query-service", version = "0.19.0" }
plugin = { path = "plugin", version = "0.19.0" }
