[package]
name = "subjective"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[package.metadata.psibase]
package-name = "TestSubjective"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
psibase_macros.workspace = true
psibase.workspace = true
serde.workspace = true
psibase-rust-workspace-hack.workspace = true
