[package]
name = "identity-pkg"
description = "Tools for exploring and confirming identities"
version = "0.19.0"
rust-version = "1.64"
edition = "2021"
publish = false


[package.metadata.psibase]
package-name = "Identity"
services = ["identity"]

[package.metadata.psibase.dependencies]
HttpServer = "0.19.0"
Sites = "0.19.0"

[lib]
crate-type = ["rlib"]

[dependencies]
identity-plugin = { path = "plugin", version = "0.19.0" }
identity = { path = "service", version = "0.19.0" }
