package host:prompt;

/// Calls that are tied to the web platform
interface web {
    use host:common/types.{error};

    /// `prompt-user` prompts the user for input. `prompt-user` will display the content at `subpath`, supplying an arbitrary payload `payload-json-str`
    /// * `subpath`: Optional: the subpath to visit on the caller's subdomain to access the prompting
    /// * `payload-json`: Optional: any data payload that the prompt page may need as a serialized JSON string
    prompt-user: func(subpath: option<string>, payload-json: option<string>) -> result<_, error>;
}

world imports {
    import web;
}