package auth-sig:plugin;

world impl {
    include accounts:plugin/imports;
    include transact:plugin/imports;
    include host:common/imports;
    include clientdata:plugin/imports;

    include transact:plugin/hook-user-auth;

    export keyvault;
    export actions;
}
