package setcode:plugin;

interface api {

    /// Upload compiled service code to the server into the namespace of the logged-in user
    /// Parameters:
    /// `code`: The compiled code as a byte array
    set-service-code: func(code: list<u8>);
}

world imports {
    import api;
}
