[package]
name = "subgroups"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
psibase.workspace = true
psibase_macros.workspace = true
serde = { version = "1.0.208", features = ["derive"] }
psibase-user-workspace-hack.workspace = true

[dev-dependencies]
subgroups-pkg = { path = "..", version = "0.22.0" }
