[package]
name = "subgroups"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
psibase.workspace = true
psibase_macros.workspace = true
serde = { version = "1.0.208", features = ["derive"] }
user-workspace-hack = { version = "0.1", path = "../../user-workspace-hack" }

[dev-dependencies]
subgroups-pkg = { path = "..", version = "0.22.0" }
