[package]
name = "r-profiles"
description = "RPC service for profiles"
version = "0.21.1"
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
psibase.workspace = true
serde.workspace = true
serde_json.workspace = true
profiles = { path = "../service", version = "0.21.1" }
async-graphql.workspace = true
user-workspace-hack = { version = "0.1", path = "../../user-workspace-hack" }
