[package]
name = "r-secrets"
description = "RPC service for secrets"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
psibase = { path = "../../../../rust/psibase/", version = "0.20.0" }
serde = "1.0"
serde_json = "1.0"
secrets = { path = "../service", version = "0.20.0" }
async-graphql = { version = "7.0.10" }
