[package]
name = "brotli-codec-pkg"
description = "Compression/decompression library"
version = "0.17.0"
edition = "2021"
rust-version = "1.64"
publish = false


[package.metadata.psibase]
package-name = "BrotliCodec"
services = ["brotli-codec"]

[package.metadata.psibase.dependencies]
Supervisor = "0.17.0"
Sites = "0.17.0"
HttpServer = "0.17.0"

[lib]
crate-type = ["rlib"]

[dependencies]
brotli-codec = { path = "service", version = "0.17.0" }
brotlicodec-plugin = { path = "plugin", version = "0.17.0" }
serde = { workspace = true }
