[workspace]
resolver = "2"
members = ["service", "plugin"]

[workspace.package]
version = "0.20.0"
rust-version = "1.64"
edition = "2021"
publish = false

[package]
name = "secrets-pkg"                      # Crate name
description = "Manages on-chain secrets"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[package.metadata.psibase]
package-name = "Secrets"
services = ["secrets"]

[package.metadata.psibase.dependencies]
HttpServer = "0.20.0"
Sites = "0.20.0"
Permissions = "0.20.0"

[lib]
crate-type = ["rlib"]

[dependencies]
secrets = { path = "service", version = "0.20.0" }
r-secrets = { path = "query-service", version = "0.20.0" }
secrets-plugin = { path = "plugin", version = "0.20.0" }
