[package]
name = "checksumtest"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.psibase]
server = "r-checksumtest"
plugin = "plugin"
data = [{ src = "../ui/dist", dst = "/" }]
postinstall = [
    { sender = "checksumtest", service = "checksumtest", method = "init", data = {} },
]

[dependencies]
psibase = { version = "0.17.0", path = "../../../../rust/psibase" }
psibase_macros = { version = "0.17.0", path = "../../../../rust/psibase_macros" }
async-graphql = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
checksumtest-pkg = { path = "..", version = "0.17.0" }
