{
 "title": "Psinode Dashboards",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "BPS",
   "type": "stat",
   "description": "Blocks produced per second",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(psinode_produced_blocks_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP QPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(psinode_http_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(psinode_transactions_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Graphql QPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by() (rate(psinode_http_requests_total{http_method=\"POST\", http_path=~\"(.*)/graphql(.*)\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by(group) (rate(psinode_tasks_user[$__rate_interval]))",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "psinode_memory_code", "legendFormat": "Code" },
    { "expr": "psinode_memory_data", "legendFormat": "Data" },
    { "expr": "psinode_memory_database", "legendFormat": "DB" },
    { "expr": "psinode_memory_wasm_code", "legendFormat": "WASM Code" },
    { "expr": "psinode_memory_wasm_memory", "legendFormat": "WASM Memory" },
    { "expr": "psinode_memory_unclassified", "legendFormat": "Unclassified" }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(psinode_transactions_succeeded[$__rate_interval])",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "rate(psinode_transactions_skipped[$__rate_interval])",
     "legendFormat": "Skipped"
    },
    {
     "expr": "rate(psinode_transactions_unprocessed[$__rate_interval])",
     "legendFormat": "Unprocessed"
    },
    {
     "expr": "rate(psinode_transactions_failed[$__rate_interval])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "RW/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(group) (rate(psinode_tasks_read[$__rate_interval]))",
     "legendFormat": "{{group}} read"
    },
    {
     "expr": "sum by(group) (rate(psinode_tasks_written[$__rate_interval]))",
     "legendFormat": "{{group}} written"
    }
   ]
  },
  {
   "title": "Page faults/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "sum by(group) (rate(psinode_tasks_page_faults[$__rate_interval]))",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "HTTP QPS Details",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(psinode_http_requests_total[$__rate_interval])",
     "legendFormat": "{{http_path}}"
    }
   ]
  }
 ]
}