[package]
name = "symbol"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.psibase]
server = "r-symbol"
plugin = "plugin"
data = [{ src = "../ui/dist", dst = "/" }]
postinstall = [
    { sender = "symbol", service = "symbol", method = "init", data = {} },
]

[dependencies]
psibase = { version = "0.19.0", path = "../../../../rust/psibase" }
psibase_macros = { version = "0.19.0", path = "../../../../rust/psibase_macros" }
async-graphql = "7.0.7"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.120"

[dev-dependencies]
symbol-pkg = { path = "..", version = "0.19.0" }

