[package]
name = "identity"
version = "0.1.0"
edition = "2021"

[dependencies]
psibase_macros = { version = "0.11.0", path = "../../../../rust/psibase_macros" }
psibase = { version = "0.11.0", path = "../../../../rust/psibase" }
serde = { version = "1", features = ["derive"] }
async-graphql = "4.0"
serde_json = "1.0.120"
# attestation = { version = "0.1.0", path = "../../Attestation/service" }
