[package]
name = "identity"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.psibase]
plugin = "plugin"
data = [{ src = "../ui/dist", dst = "/" }]
postinstall = [
    { sender = "identity", service = "identity", method = "init", rawData = "0000" },
]

[dependencies]
psibase_macros = { path = "../../../../rust/psibase_macros", version = "0.14.0" }
psibase = { path = "../../../../rust/psibase", version = "0.14.0" }
serde = { version = "1.0.208", features = ["derive"] }
async-graphql = "7.0.7"
serde_json = "1.0.120"
