import {
    QualifiedDynCallArgs,
    QualifiedFunctionCallArgs,
    QualifiedResourceCallArgs,
} from "@psibase/common-lib";

import { RecoverableErrorPayload } from "./plugin/errors";

export type Result<T, E> = T | E;

export interface HttpRequest {
    uri: string;
    method: string;
    headers: { key: string; value: string }[];
    body?: BodyType;
}

export interface HttpResponse {
    status: number;
    headers: { key: string; value: string }[];
    body: BodyType | null;
}

export interface BodyType {
    tag: string;
    val: Uint8Array | string;
}

export interface PluginPostDetails {
    endpoint: string;
    headers: [string, string][];
    body: BodyType;
}

// This is the interface linked to the host plugin
export interface HostInterface {
    // Get the value associated with the specified `key`
    //
    // If the key-value pair exists, return it. Otherwise, it returns null.
    dbGet: (duration: number, key: string) => Uint8Array | null;

    // Set the value associated with the key in the store. If the key already
    // exists in the store, it overwrites the value.
    //
    // If the key does not exist in the store, it creates a new key-value pair.
    dbSet: (duration: number, key: string, value: Uint8Array) => void;

    // Delete the key-value pair associated with the key in the store.
    //
    // If the key does not exist in the store, it does nothing.
    dbRemove: (duration: number, key: string) => void;

    // Get the chain ID of the current chain from which this host was served.
    getChainId: () => string;

    // Interface for the autogenerated proxy package
    syncCall: (args: QualifiedFunctionCallArgs) => any;

    syncCallResource: (args: QualifiedResourceCallArgs) => any;

    syncCallDyn: (args: QualifiedDynCallArgs) => any;

    sendRequest: (
        req: HttpRequest,
    ) => Result<HttpResponse, RecoverableErrorPayload>;

    getActiveApp(): string;

    getServiceStack(): string[];

    getRootDomain(): string;

    requestPrompt: (id: string) => Result<void, string>;
}
