[package]
name = "fractals-pkg"              # Crate name
description = "Fractal governance"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "Fractals"
services = ["fractals"]

[package.metadata.psibase.dependencies]
HttpServer = "0.22.0"
Sites = "0.22.0"

[lib]
crate-type = ["rlib"]

[dependencies]
fractals = { path = "service", version = "0.22.0" }
r-fractals = { path = "query-service", version = "0.22.0" }
fractals-plugin = { path = "plugin", version = "0.22.0" }
user-workspace-hack = { version = "0.1", path = "../user-workspace-hack" }
