[workspace]
resolver = "2"
members = ["service", "plugin", "query-service", "query-schema"]

[workspace.package]
version = "0.21.0"
rust-version = "1.64"
edition = "2021"
publish = false

[package]
name = "fractals-pkg"              # Crate name
description = "Fractal governance"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[package.metadata.psibase]
package-name = "Fractals"
services = ["fractals"]

[package.metadata.psibase.dependencies]
HttpServer = "0.21.0"
Sites = "0.21.0"

[lib]
crate-type = ["rlib"]

[dependencies]
fractals = { path = "service", version = "0.21.0" }
r-fractals = { path = "query-service", version = "0.21.0" }
plugin = { path = "plugin", version = "0.21.0" }
