[workspace]
resolver = "2"
members = ["service", "plugin"]

[workspace.package]
version = "0.17.0"
rust-version = "1.64"
edition = "2021"
publish = false

[package]
name = "checksumtest-pkg"              # Crate name
description = "An example application"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[package.metadata.psibase]
package-name = "Checksumtest"
services = ["checksumtest"]

[package.metadata.psibase.dependencies]
HttpServer = "0.17.0"
Sites = "0.17.0"

[lib]
crate-type = ["rlib"]

[dependencies]
checksumtest = { path = "service", version = "0.17.0" }
r-checksumtest = { path = "query-service", version = "0.17.0" }
plugin = { path = "plugin", version = "0.17.0" }
