package demoapp1:example;

interface intf {
    use common:plugin/types.{error};
    helloworld2: func() -> result<string, error>;
}

world example {
    import invite:plugin/inviter;

    export helloworld: func() -> string;
    export intf;
}
