[package]
name = "addcheckinit"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition = "2021"
publish = false

[package.metadata.psibase]
package-name = "addcheckinit"
server = "addcheckinit"

[package.metadata.psibase.dependencies]
HttpServer = "0.20.0"

[dependencies]
psibase = { path = "../../../psibase" }
psibase_macros = { path = "../../../psibase_macros" }
async-graphql.workspace = true
serde = { version = "1.0.209", features = ["derive"] }

[dev-dependencies]
psimacrotest = { path = "../.." }
