[package]
name = "addcheckinit"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "addcheckinit"
server = "addcheckinit"

[package.metadata.psibase.dependencies]
HttpServer = "0.21.0"

[dependencies]
psibase.workspace = true
psibase_macros.workspace = true
async-graphql.workspace = true
serde = { version = "1.0.209", features = ["derive"] }
psibase-rust-workspace-hack.workspace = true

[dev-dependencies]
psimacrotest = { path = "../.." }
