[package]
name = "auth-cred"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
psibase = { version = "0.20.0", path = "../../../../rust/psibase" }
psibase_macros = { version = "0.20.0", path = "../../../../rust/psibase_macros" }
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.120"
credentials = { path = "../service", version = "0.20.0" }

[dev-dependencies]
credentials-pkg = { path = "..", version = "0.20.0" }
