[workspace]
resolver = "2"
members = ["service", "query", "plugin"]

[workspace.package]
version = "0.1.0"
rust-version = "1.64"
edition = "2021"
publish = false
repository = "https://github.com/gofractally/psibase"
homepage = "https://psibase.io"

[package]
name = "workshop_package"
version = "0.1.0"

[package.metadata.psibase]
package-name = "workshop"
description = "Workshop for psibase apps"
services = ["workshop"]

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[lib]
crate-type = ["rlib"]

[dependencies]
workshop = { path = "service" }
r-workshop = { path = "query" }
workshop-plugin = { path = "plugin" }
