[package]
name = "fractals"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.psibase]
server = "r-fractals"
plugin = "fractals-plugin"
data = [{ src = "../ui/dist", dst = "/" }]
postinstall = [
    { sender = "fractals", service = "sites", method = "enablespa", rawData = "010001" },
]


[dependencies]
psibase.workspace = true
psibase_macros.workspace = true
evaluations = { path = "../../Evaluations/service", version = "0.21.0" }
async-graphql.workspace = true
serde.workspace = true
serde_json.workspace = true
user-workspace-hack = { version = "0.1", path = "../../user-workspace-hack" }

[dev-dependencies]
fractals-pkg = { path = "..", version = "0.21.0" }
