[package]
name = "app_registry"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition = "2021"
publish = false

[package.metadata.psibase]
package-name = "AppRegistry"
description = "Registry for psibase apps"
services = ["tpack"]

[lib]
crate-type = ["rlib"]

[dependencies]
tpack = { path = "service", version = "0.12.0" }
r-tpack = { path = "query", version = "0.12.0" }
