[package]
name = "app_registry_package"
edition = "2021"
version = "0.1.0"

[package.metadata.psibase]
package-name = "AppRegistry"
description = "Registry for psibase apps"
services = ["app-registry"]

[lib]
crate-type = ["rlib"]

[dependencies]
app-registry = { path = "service", version = "0.1.0" }
r-app-reg = { path = "query", version = "0.1.0" }
