[package]
name = "workshop"
description = "Workshop Service"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
publish = false

[package.metadata.psibase]
server = "r-workshop"
plugin = "workshop-plugin"
data = [{src = "../ui/dist", dst = "/"}]

[package.metadata.psibase.dependencies]
HttpServer = "0.13.0"

[dependencies]
psibase = { path = "../../../../rust/psibase" }
serde = { version = "1", features = ["derive"] }
async-graphql = "7.0.7"
serde_json = "1.0.120"

[dev-dependencies]
workshop_package = { path = ".." }
