[package]
name = "x-admin"
version = "0.16.0"
repository = "https://github.com/gofractally/psibase"
edition = "2021"
publish = false

[dependencies]
wit-bindgen-rt = { version = "0.39.0", features = ["bitflags"] }
psibase = { path = "../../../../../rust/psibase/", version = "0.16.0" }
chrono = { version = "0.4" }
pem = "3.0.4"
spki = "0.7"
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "psibase:x-admin"
