package {{project-name}}:plugin;

world impl {
    include host:call-context/imports;
    include host:authed-http/imports;
    include transact:plugin/imports;
    include permissions:plugin/imports;

    export api;
    export queries;
}
