package {{project-name}}:plugin;

interface api {
    set-example-thing: func(thing: string);
}

interface queries {
    use host:common/types.{error};
    get-example-thing: func() -> result<string, error>;
}

world imports {
    import api;
    import queries;
}
