[package]
name = "registry"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.psibase]
server = "r-registry"
plugin = "registry-plugin"
postinstall = [{ sender = "registry", service = "registry", method = "init" }]

[package.metadata.psibase.dependencies]
HttpServer = "0.22.0"
Sites = "0.22.0"

[dependencies]
psibase.workspace = true
serde.workspace = true
async-graphql.workspace = true
serde_json.workspace = true
url = "2.5.2"
user-workspace-hack = { version = "0.1", path = "../../user-workspace-hack" }

[dev-dependencies]
registry-pkg = { path = "..", version = "0.22.0" }
