[package]
name = "brotli-codec"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.psibase]
plugin = "brotli-codec-plugin"

[dependencies]
brotli = { version = "7.0.0" }
base64 = { version = "0.22" }
anyhow = { version = "1.0" }
psibase.workspace = true
serde.workspace = true
psibase-user-workspace-hack.workspace = true

[dev-dependencies]
brotli-codec-pkg = { path = "..", version = "0.21.0" }
