package permissions:plugin;

interface admin {
    use host:common/types.{error};
    // caller should be permissions
    is-valid-request: func(caller: string, callee: string) -> result<bool, error>;
}

world impl {
    include host:common/imports;
    include transact:plugin/imports;
    include sites:plugin/imports;
    include clientdata:plugin/imports;

    export api;
    export users;
    export admin;
}
