package permissions:plugin;

interface admin {
    use host:common/types.{error};

    is-valid-request: func(id: string, caller: string, callee: string) -> result<bool, error>;
}

world impl {
    include host:common/imports;
    include clientdata:plugin/imports;

    export api;
    export users;
    export admin;
}
