[package]
name = "branding"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
publish = false

[package.metadata.psibase]
server = "branding"
plugin = "plugin"
data = [{ src = "../ui/dist", dst = "/" }]

[dependencies]
psibase = { path = "../../../../rust/psibase", version = "0.17.0" }
psibase_macros = { path = "../../../../rust/psibase_macros", version = "0.17.0" }
async-graphql = "=7.0.17"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.120"

[dev-dependencies]
branding-pkg = { path = "..", version = "0.17.0" }
