[package]
name = "branding"
version = "0.1.0"
edition = "2021"

[dependencies]
psibase = { path = "../../../../rust/psibase" }
psibase_macros = { path = "../../../../rust/psibase_macros" }
async-graphql = "7.0.7"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.120"
