[package]
name = "staged-tx"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
publish = false

[package.metadata.psibase]
flags = ["allowSudo"]
server = "r-staged-tx"
plugin = "plugin"
postinstall = [
    { sender = "staged-tx", service = "staged-tx", method = "init", rawData = "0000" },
]

[dependencies]
async-graphql = { version = "7.0.10" }
psibase = { path = "../../../../rust/psibase/" }
serde = { version = "1.0.213", features = ["derive"] }
serde_json = { version = "1.0.100" }
sha2 = { version = "0.10" }
pem = { version = "3.0.4" }

[dev-dependencies]
staged-tx-pkg = { path = "..", version = "0.14.0" }
