package aes:plugin;

interface with-password {
    use host:common/types.{error};

    /// Encrypts data using a password.
    /// 
    /// Arguments:
    /// - password: The password to use for encryption
    /// - data: The data to encrypt
    /// - salt: The salt to use for encryption
    /// 
    /// Returns:
    /// - The encrypted data
    encrypt: func(password: list<u8>, data: list<u8>, salt: string) -> list<u8>;

    /// Decrypts data using a password
    /// 
    /// Arguments:
    /// - password: The password to use for decryption
    /// - encrypted: The encrypted data to decrypt
    /// - salt: The salt to use for decryption
    /// 
    /// Returns:
    /// - The decrypted data
    decrypt: func(password: list<u8>, encrypted: list<u8>, salt: string) -> result<list<u8>, error>;
}

world imports {
    import with-password;
}
