[package]
name = "r-workshop"
description = "Query service for Workshop"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition = "2021"
publish = false

[dependencies]
psibase = { path = "../../../../rust/psibase" }
serde = "1.0"
workshop = { path = "../service" }
async-graphql = "7.0.7"

[dev-dependencies]
workshop_package = { path = ".." }