[package]
name = "r-registry"
description = "Query service for Registry"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
psibase.workspace = true
serde.workspace = true
serde-aux.workspace = true
registry = { path = "../service", version = "0.21.0" }
async-graphql.workspace = true
psibase-user-workspace-hack.workspace = true

[dev-dependencies]
registry-pkg = { path = "..", version = "0.21.0" }
