[package]
name = "r-registry"
description = "Query service for Registry"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
psibase = { path = "../../../../rust/psibase", version = "0.20.0" }
serde = "1.0"
serde-aux = "4.7.0"
registry = { path = "../service", version = "0.20.0" }
async-graphql = "=7.0.17"

[dev-dependencies]
registry-pkg = { path = "..", version = "0.20.0" }
