[package]
name = "r-registry"
description = "Query service for Registry"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
psibase.workspace = true
serde.workspace = true
serde-aux.workspace = true
registry = { path = "../service", version = "0.22.0" }
async-graphql.workspace = true
user-workspace-hack = { version = "0.1", path = "../../user-workspace-hack" }

[dev-dependencies]
registry-pkg = { path = "..", version = "0.22.0" }
