package supervisor:test;

interface tests {
    use wasi:keyvalue/store@0.2.0-draft.{error};
    kv-test: func() -> result<_, error>;
}

world example {
    include wasi:keyvalue/imports@0.2.0-draft;
    include host:common/imports;
    export tests;
}
