[package]
name = "auth-invite"
version.workspace = true
edition.workspace = true

[dependencies]
wit-bindgen-rt.workspace = true
psibase.workspace = true

[lib]
crate-type = ["cdylib"]

[package.metadata.component.target]
world = "impl"

[package.metadata.component]
package = "auth-invite:plugin"

[package.metadata.component.target.dependencies]
"host:common" = { path = "../../Host/plugin/common/wit/world.wit" }
"host:crypto" = { path = "../../Host/plugin/crypto/wit/world.wit" }
"host:types" = { path = "../../Host/plugin/types/wit/world.wit" }
"invite:plugin" = { path = "../../Invite/plugin/wit/world.wit" }
"clientdata:plugin" = { path = "../../ClientData/plugin/wit/world.wit" }
"transact:plugin" = { path = "../../../system/Transact/plugin/wit/world.wit" }
