[workspace]
resolver = "2"
members = ["service", "plugin"]

[workspace.package]
version = "0.1.0"
rust-version = "1.64"
edition = "2021"
repository = "https://github.com/gofractally/psibase"
homepage = "https://psibase.io"
publish = false

[package]
name = "webmail_package"

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[package.metadata.psibase]
package-name = "Webmail"
description = "Basic email app"
services = ["webmail"]
data = [{ src = "ui/dist/", dst = "/" }]

[lib]
crate-type = ["rlib"]

[dependencies]
webmail = { path = "service" }
plugin = { path = "plugin" }
