[package]
name = "identity-pkg"
description = "Tools for exploring and confirming identities"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "Identity"
services = ["identity"]

[package.metadata.psibase.dependencies]
HttpServer = "0.21.0"
Sites = "0.21.0"

[lib]
crate-type = ["rlib"]

[dependencies]
identity = { path = "service", version = "0.21.0" }
identity-plugin = { path = "plugin", version = "0.21.0" }
