[workspace]
members = [
    "plugin-workspace-hack",
    "system/Accounts/plugin/accounts/",
    "system/Accounts/plugin/account_tokens/",
    "system/AuthAny/plugin/",
    "system/AuthDelegate/plugin/",
    "system/AuthSig/plugin/",
    "system/Transact/plugin/",
    "system/SetCode/plugin/",
    "system/Producers/plugin/",
    "user/Aes/plugin",
    "user/Base64/plugin",
    "user/ClientData/plugin",
    "user/Host/plugin/auth",
    "user/Host/plugin/crypto",
    "user/Host/plugin/common",
    "user/Host/plugin/prompt",
    "user/Host/plugin/types",
    "user/Invite/plugin",
    "user/Invite/plugin_AuthInvite",
    "user/Kdf/plugin",
    "user/Sites/plugin",
    "user/Packages/plugin",
    "user/Permissions/plugin",
    "user/WebCrypto/plugin",
    "user/FractalCore/plugin",
    "user/Workshop/plugin",
    "user/Config/plugin",
]
resolver = "2"

exclude = [
    "user/CommonApi/common/packages/component-parser",
    "local/XAdmin/ui/wasm",
    # other excludes
]

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[workspace.package]
version = "0.21.0"
edition = "2021"
rust-version = "1.64"
repository = "https://github.com/gofractally/psibase"
homepage = "https://psibase.io"
license = "MIT"
publish = false

[workspace.dependencies]
# Common dependencies for plugins
async-graphql = "=7.0.17"
psibase = { path = "../rust/psibase", version = "0.21.0" }
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
psibase-plugin-workspace-hack = { version = "0.1.0", path = "plugin-workspace-hack" }
# Standard version for cargo-component 0.15.0
wit-bindgen-rt = { version = "0.30.0", features = ["bitflags"] }
