[package]
name = "staged-tx-pkg"
description = "Library for proposing and executing staged transactions"
version = "0.19.0"

rust-version = "1.64"
edition = "2021"
repository = "https://github.com/gofractally/psibase"
homepage = "https://psibase.io"
publish = false

[package.metadata.psibase]
package-name = "StagedTx"
services = ["staged-tx"]

[package.metadata.psibase.dependencies]
Supervisor = "0.19.0"
Sites = "0.19.0"
HttpServer = "0.19.0"


[lib]
crate-type = ["rlib"]

[dependencies]
staged-tx = { path = "service", version = "0.19.0" }
r-staged-tx = { path = "query-service", version = "0.19.0" }
staged-tx-plugin = { path = "plugin", version = "0.19.0" }
