[package]
name = "r-app-reg"
description = "Query service for AppRegistry"
edition = "2021"
version = "0.1.0"
publish = false

[package.metadata.psibase]
plugin = "app-registry-plugin"

[dependencies]
psibase = { path = "../../../../rust/psibase" }
serde = "1.0"
app-registry = { path = "../service", version = "0.1.0" }
async-graphql = "7.0.7"
