name: On PR Closed - Copy Issue Labels

on:
  pull_request:
    types:
      - closed

jobs:

  copy-labels:
    name: Copy linked issue labels
    runs-on: ubuntu-latest
    steps:
      - name: copy-labels
        uses: michalvankodev/copy-issue-labels@v1.2.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          from-title: true
