name: On Release - Propagate

on:
  release:
    types: [published]

jobs:

  build-new-CLI-versions:
    name: Build new CLI version
    runs-on: ubuntu-latest
    steps:
      - name: Building ${{ github.event.release.name }} images
        id: output
        run: true
      - name: Trigger CLI image builds
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_DISPATCHER_TOKEN }}
        run: |
          version=${{ github.event.release.name }}
          gh workflow run cli.yml -f version=$version -R ${{ github.repository_owner }}/image-builders
      - name: Update dev-chat
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            🎉 New Psibase release 🎉
            [${{ github.ref_name }}](https://github.com/${{ github.repository }}/releases/tag/${{ github.event.release.name }})
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - uses: dtolnay/rust-toolchain@1.86.0
      - name: Publish crates to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          if [[ -z "$CARGO_REGISTRY_TOKEN" ]]; then
            echo "CARGO_REGISTRY_TOKEN secret is not set" >&2
            exit 1
          fi
          cd rust
          ./scripts/publish.sh
