name: On Update - Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "release/*"
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled]

jobs:
  build:
    name: Run Builds
    uses: ./.github/workflows/ubuntu-builder.yml
